/**
 * Technology knowledge base — searchable concept cards.
 * Each card answers the same eight questions so concepts are comparable.
 * Numbers cited are typical orders of magnitude (simulation assumptions).
 */

import type { KnowledgeCard } from '../domain/types'

const c = (card: KnowledgeCard) => card

export const KNOWLEDGE_CARDS: KnowledgeCard[] = [
  // ======================================================================
  // AUDIO
  // ======================================================================
  c({
    id: 'pcm', term: 'PCM (Pulse-Code Modulation)', category: 'audio',
    whatIsIt: 'Raw digital audio: the waveform sampled N times per second, each sample stored as a number (commonly 16-bit signed).',
    whyExists: 'Sound is analog; computers need numbers. PCM is the most direct possible encoding — no compression, no model, just samples.',
    problemSolved: 'A universal, zero-decode representation every audio library, model and DSP routine understands.',
    whereInVoice: 'The internal currency of the pipeline: gateways decode carrier audio to PCM, STT consumes PCM, TTS emits PCM.',
    alternatives: ['Compressed codecs (Opus, MP3) for transport/storage', 'Companded G.711 for telephony'],
    limitations: ['Big: 16 kHz mono PCM16 is 256 kbit/s', 'No error resilience — a lost chunk is a gap'],
    scaling: 'Bandwidth scales linearly with sample rate × bit depth × channels; at 10k concurrent calls the media tier moves gigabits of PCM.',
    failureModes: ['Endianness/format mismatches produce loud static', 'Sample-rate mislabeling produces chipmunk/slow-motion audio'],
    related: ['sample-rate', 'codecs', 'resampling'],
    keyNumbers: [
      { label: '16 kHz mono PCM16', value: '32 KB/s', note: '256 kbit/s' },
      { label: '8 kHz mono PCM16', value: '16 KB/s', note: 'telephony rate after decode' },
    ],
  }),
  c({
    id: 'codecs', term: 'Audio codecs (G.711, Opus, MP3)', category: 'audio',
    whatIsIt: 'Algorithms that shrink audio for transport or storage: G.711 (simple companding, 64 kbit/s), Opus (modern low-latency, 6–510 kbit/s), MP3/AAC (perceptual, file-oriented).',
    whyExists: 'Raw PCM is too big for networks that charge for bytes and too fragile for networks that lose packets.',
    problemSolved: 'Fit voice into telephone trunks (G.711), internet real time (Opus) and archives (MP3/FLAC), each optimised for its constraint.',
    whereInVoice: 'G.711 mu-law/A-law arrives from the PSTN; Opus arrives from browsers; MP3/FLAC go to recording storage. The gateway converts between them.',
    alternatives: ['Raw PCM inside your own network (LAN bandwidth is free-ish)'],
    limitations: ['Lossy codecs discard information permanently; each re-encode compounds the loss', 'MP3/AAC carry >100 ms algorithmic delay — wrong for live paths'],
    scaling: 'Codec choice sets per-call bandwidth and gateway CPU; Opus encode is ~10–40× the CPU of G.711 table lookup (assumption).',
    failureModes: ['Codec mismatch in SDP negotiation → one-way or no audio', 'Transcoding chains silently degrading quality'],
    related: ['pcm', 'opus', 'rtp', 'resampling'],
  }),
  c({
    id: 'opus', term: 'Opus', category: 'audio',
    whatIsIt: 'The modern real-time audio codec: 2.5–60 ms frames, 6–510 kbit/s, narrowband to fullband, with in-band FEC and packet-loss concealment.',
    whyExists: 'Real-time internet audio needed one codec good at both speech and music, at low delay, royalty-free. Opus won; WebRTC mandates it.',
    problemSolved: 'High-quality speech at ~24–32 kbit/s that stays intelligible through packet loss.',
    whereInVoice: 'Every browser call. Media servers decode Opus → PCM for STT and encode PCM → Opus on the way back.',
    alternatives: ['G.711 (telephony interop)', 'raw PCM over WebSocket (LAN/server-side)'],
    limitations: ['~26.5 ms algorithmic delay', 'Real encode CPU at scale', 'PSTN does not speak it — transcoding at the phone boundary is unavoidable'],
    scaling: 'Encode CPU dominates WebRTC media servers; capacity per instance is often an Opus-CPU number.',
    failureModes: ['CPU saturation → encode deadline misses → choppy audio fleet-wide'],
    related: ['codecs', 'webrtc', 'rtp'],
    keyNumbers: [{ label: 'Voice sweet spot', value: '24–32 kbit/s', note: 'transparent for speech (assumption)' }],
  }),
  c({
    id: 'sample-rate', term: 'Sample rate', category: 'audio',
    whatIsIt: 'How many measurements of the waveform are taken per second: 8 kHz (telephony), 16 kHz (wideband/STT), 24–48 kHz (TTS/browser).',
    whyExists: 'Nyquist: a rate of N captures frequencies up to N/2. Speech energy matters up to ~8 kHz; telephony historically settled on 8 kHz (≤3.4 kHz usable).',
    problemSolved: 'The dial that trades fidelity against bandwidth and compute.',
    whereInVoice: 'The mismatch machine: 8 kHz from phones, 16 kHz into STT, 24 kHz out of TTS, 48 kHz in browsers — hence resampling everywhere.',
    alternatives: [],
    limitations: ['Upsampling adds no information — 8 kHz audio resampled to 16 kHz is still phone-quality', 'Downsampling permanently discards highs'],
    scaling: 'Linear in bandwidth and buffer sizes.',
    failureModes: ['Rate mislabeling (pitch shift)', 'Hidden SDK resampling costing unaccounted latency and quality'],
    related: ['pcm', 'resampling', 'stt'],
    keyNumbers: [{ label: 'Phone STT accuracy penalty', value: 'measurable', note: '8 kHz band-limit removes cues models use (simulation reflects this)' }],
  }),
  c({
    id: 'resampling', term: 'Resampling', category: 'audio',
    whatIsIt: 'Converting audio between sample rates with interpolation filters (e.g. 8 kHz → 16 kHz for STT, 24 kHz → 8 kHz for the carrier).',
    whyExists: 'Every component in a voice pipeline was designed against a different "natural" rate; something must reconcile them.',
    problemSolved: 'Lets a 24 kHz TTS voice reach an 8 kHz phone line and lets 8 kHz phone audio feed a 16 kHz STT model.',
    whereInVoice: 'Inside the media gateway — ideally exactly once per direction.',
    alternatives: ['Choosing components with matching native rates (rarely fully possible)'],
    limitations: ['Integer ratios (8→16) are cheap and clean; awkward ratios (16→22.05) need polyphase filters — more CPU, more artifacts', 'Each pass adds a little latency and (downward) loses content'],
    scaling: 'CPU per call per conversion; chains of conversions multiply.',
    failureModes: ['Round-trip chains (8→16→22.05→8) burning latency and quality for nothing — the Audio Lab detects exactly this'],
    related: ['sample-rate', 'pcm', 'codecs'],
  }),

  // ======================================================================
  // NETWORKING
  // ======================================================================
  c({
    id: 'websocket', term: 'WebSocket', category: 'networking',
    whatIsIt: 'A persistent, bidirectional message channel over one TCP connection, established by an HTTP Upgrade handshake.',
    whyExists: 'HTTP is request→response→done; a live conversation needs both sides free to send at any moment for minutes on end.',
    problemSolved: 'Continuous streaming of audio frames and JSON events without per-message connection overhead, through any firewall that allows HTTPS.',
    whereInVoice: 'Everywhere: telephony media streams, STT/TTS provider APIs, browser fallback transport, internal service streams.',
    alternatives: ['WebRTC (UDP; better on lossy last miles)', 'gRPC streams (server-to-server)', 'SSE (server→client only)'],
    limitations: ['TCP head-of-line blocking: one lost packet stalls everything behind it', 'Idle timeouts on LBs silently kill quiet connections', 'One connection = one server: sticky by nature'],
    scaling: 'Count connections, not requests: memory + file descriptor + bandwidth per connection; blast radius per server = its connection count.',
    failureModes: ['1006 abnormal closures', 'backpressure when the peer reads slower than you write', 'reconnect storms after LB restarts'],
    related: ['backpressure', 'webrtc', 'load-balancing'],
    keyNumbers: [{ label: '16 kHz PCM16 over WS', value: '~640 B / 20 ms frame', note: '+ framing overhead' }],
  }),
  c({
    id: 'webrtc', term: 'WebRTC', category: 'networking',
    whatIsIt: 'The browser\'s real-time media stack: capture, Opus encode, SRTP transport, ICE NAT traversal, echo cancellation, jitter buffering — one API.',
    whyExists: 'Real-time audio from arbitrary browsers behind arbitrary NATs was effectively impossible; WebRTC standardised the entire solution.',
    problemSolved: 'Carrier-grade audio behaviour (UDP, FEC, AEC, adaptation) from a web page with no install.',
    whereInVoice: 'The browser edge of browser-channel agents; also increasingly the client SDK transport for realtime S2S APIs.',
    alternatives: ['WebSocket + AudioWorklet PCM (simpler, TCP-bound)', 'native SDKs'],
    limitations: ['Operational surface: signalling, STUN/TURN, media servers', 'Debugging is specialised (ICE, SDP, getStats)'],
    scaling: 'Media servers are CPU-bound on codec work: hundreds (not thousands) of streams per instance (assumption); TURN adds relay bandwidth for the 10–20% who need it.',
    failureModes: ['ICE failure behind strict firewalls', 'quality collapse past ~10% packet loss', 'autoplay/mic-permission UX failures'],
    related: ['ice', 'stun-turn', 'sdp', 'opus', 'rtp'],
  }),
  c({
    id: 'ice', term: 'ICE (Interactive Connectivity Establishment)', category: 'networking',
    whatIsIt: 'The algorithm that finds a working network path between two peers: gather candidate addresses (host, STUN-reflexive, TURN-relay), probe pairs, pick the best.',
    whyExists: 'NAT means neither side knows an address the other can actually reach; ICE turns "try everything" into a protocol.',
    problemSolved: 'Direct peer connectivity where possible, relayed connectivity where not — automatically.',
    whereInVoice: 'Every WebRTC session start; typically 100–500 ms of the connection setup.',
    alternatives: ['Always-relay through your media server (simple, adds a hop for everyone)'],
    limitations: ['Adds setup latency', 'fails outright on hostile firewalls without TURN-over-TLS'],
    scaling: 'Stateless-ish; the real scaling cost is the TURN fleet it falls back to.',
    failureModes: ['ICE failed = signalling fine, no media — the "connected but silent" bug class'],
    related: ['stun-turn', 'webrtc', 'sdp'],
  }),
  c({
    id: 'stun-turn', term: 'STUN & TURN', category: 'networking',
    whatIsIt: 'STUN: a mirror that tells a client its public address/port. TURN: a relay that forwards media when no direct path exists.',
    whyExists: 'NAT hides clients; some NATs/firewalls block even STUN-assisted paths, so a relay of last resort is required.',
    problemSolved: 'STUN makes direct paths possible for most users; TURN makes connectivity certain for the rest.',
    whereInVoice: 'Any browser-channel deployment. Enterprise networks are heavy TURN users.',
    alternatives: ['Media servers on public IPs (server-anchored calls reduce, not remove, the need)'],
    limitations: ['TURN pays double bandwidth (in + out) per relayed call', 'must be deployed per region — a relay across an ocean adds that ocean to every packet'],
    scaling: 'Bandwidth-bound: size for (relayed-fraction × concurrent × per-call bitrate) × 2.',
    failureModes: ['Missing regional TURN → far-user latency', 'TURN quota exhaustion → connection failures for exactly the users with the worst networks'],
    related: ['ice', 'webrtc'],
    keyNumbers: [{ label: 'Relayed users', value: '~10–20%', note: 'assumption; higher in enterprises' }],
  }),
  c({
    id: 'rtp', term: 'RTP (Real-time Transport Protocol)', category: 'networking',
    whatIsIt: 'UDP packets carrying media with sequence numbers, timestamps and source IDs; the transport of telephony and WebRTC media alike.',
    whyExists: 'TCP retransmission is wrong for live audio: a late packet is worthless. RTP ships fast and lets the receiver conceal loss.',
    problemSolved: 'Timely delivery with enough metadata (seq, timestamp) for the receiver to reorder, conceal and synchronise.',
    whereInVoice: 'Carrier ↔ SBC ↔ media gateway legs; inside WebRTC as SRTP.',
    alternatives: ['WebSocket/TCP audio (simpler, HOL-blocking)'],
    limitations: ['No delivery guarantee (by design)', 'NAT-hostile: needs symmetric RTP/SBC help'],
    scaling: 'Per-call bandwidth × concurrency; packets/sec (50/call/direction) stresses NICs and kernels before bytes do.',
    failureModes: ['One-way audio (NAT/firewall asymmetry)', 'jitter/loss degrading STT accuracy invisibly'],
    related: ['rtcp', 'jitter-buffer', 'sip', 'opus'],
    keyNumbers: [{ label: 'G.711 + headers', value: '~87 kbit/s', note: 'per direction per call' }],
  }),
  c({
    id: 'rtcp', term: 'RTCP', category: 'networking',
    whatIsIt: 'RTP\'s companion control stream: periodic receiver/sender reports of loss, jitter and round-trip time.',
    whyExists: 'UDP media gives no feedback; RTCP is how each end learns what the network is doing to the audio.',
    problemSolved: 'Quality telemetry (and, in WebRTC, the input to bitrate adaptation).',
    whereInVoice: 'Quietly alongside every RTP stream; surfaced in WebRTC getStats() and SBC dashboards.',
    alternatives: ['Application-level quality pings (reinventing it, worse)'],
    limitations: ['Report intervals are seconds — trends, not instant alarms'],
    scaling: 'Negligible bandwidth (~5% budget).',
    failureModes: ['Ignoring RTCP = flying blind on audio quality; MOS complaints arrive by ticket instead of dashboard'],
    related: ['rtp', 'observability'],
  }),
  c({
    id: 'jitter-buffer', term: 'Jitter buffer', category: 'networking',
    whatIsIt: 'A small playout queue that absorbs variance in packet arrival times so audio plays smoothly.',
    whyExists: 'Networks deliver packets at irregular intervals; ears demand perfectly regular samples.',
    problemSolved: 'Turns bursty arrival into smooth playback at the cost of a small fixed delay.',
    whereInVoice: 'At every media-receiving endpoint: gateway ingress, browser playback, phone handsets.',
    alternatives: ['None — only fixed vs adaptive sizing'],
    limitations: ['Every ms of buffer is a ms of latency', 'adaptive buffers grow under bad networks — latency creep users notice'],
    scaling: 'Memory per call; trivial except at extreme concurrency.',
    failureModes: ['Too small → crackles/gaps', 'unbounded growth → seconds of drift after network trouble'],
    related: ['rtp', 'latency-perception'],
    keyNumbers: [{ label: 'Typical target', value: '20–60 ms', note: 'adaptive; simulation default 40 ms' }],
  }),
  c({
    id: 'backpressure', term: 'Backpressure', category: 'networking',
    whatIsIt: 'What happens when a producer sends faster than a consumer processes: queues grow — and the design question is what you do about it.',
    whyExists: 'Every pair of connected components has mismatched speeds sometimes; without a policy, buffers grow until memory or latency explodes.',
    problemSolved: 'A named policy (block, drop-oldest, shed load) converts an inevitable mismatch into a bounded, observable behaviour.',
    whereInVoice: 'Audio frames into a slow STT, TTS chunks into a slow carrier link, events into a lagging queue consumer.',
    alternatives: [],
    limitations: ['For live audio, "block" is not an option — dropping oldest audio is usually right (stale audio is worthless)'],
    scaling: 'The signals (queue depth, buffered bytes) are your most honest load metrics.',
    failureModes: ['Unbounded buffers → memory death and compounding latency', 'silent drops without metrics → mystery audio gaps'],
    related: ['websocket', 'queues'],
  }),

  // ======================================================================
  // TELEPHONY
  // ======================================================================
  c({
    id: 'pstn', term: 'PSTN', category: 'telephony',
    whatIsIt: 'The public switched telephone network: the global system behind every phone number.',
    whyExists: 'A century of interoperable voice infrastructure; the universal reach layer no app installs can match.',
    problemSolved: 'Anyone with any phone anywhere can reach your agent by dialling a number.',
    whereInVoice: 'The left edge of every phone-channel architecture, reached via CPaaS or SIP trunks.',
    alternatives: ['App/browser calling (better audio, requires your software in hand)'],
    limitations: ['8 kHz band-limited audio forever', 'per-minute pricing', 'regulation everywhere (numbering, recording consent, spam rules — treat specifics as legal questions)'],
    scaling: 'Bought, not built: channel counts and calls-per-second are contract terms.',
    failureModes: ['Carrier route outages', 'number reputation/spam-labelling killing outbound answer rates'],
    related: ['sip', 'sip-trunking', 'dtmf'],
  }),
  c({
    id: 'sip', term: 'SIP', category: 'telephony',
    whatIsIt: 'Session Initiation Protocol: the HTTP-like text protocol that sets up, modifies and ends calls (INVITE / 200 OK / ACK / BYE / REFER).',
    whyExists: 'Telephony needed a standard way for unrelated systems to negotiate calls and media parameters.',
    problemSolved: 'Interoperable call control: who is calling, what codecs, where to send media (via its SDP payload), transfers, holds.',
    whereInVoice: 'Between your SBC/telephony layer and carriers or contact-centre platforms. CPaaS hides it behind webhooks.',
    alternatives: ['Proprietary CPaaS APIs (SIP still runs underneath)'],
    limitations: ['NAT-hostile (addresses inside message bodies)', 'a sprawling spec — interop quirks are a career'],
    scaling: 'Signalling scales easily; the stateful SBC edge is what needs pairs and capacity planning.',
    failureModes: ['Registration/trunk failures', 'SDP mismatches → connected-but-silent calls', 'retransmission storms on packet loss'],
    related: ['sdp', 'rtp', 'sip-trunking'],
  }),
  c({
    id: 'sdp', term: 'SDP (Session Description Protocol)', category: 'telephony',
    whatIsIt: 'The offer/answer document inside SIP and WebRTC signalling: codecs supported, IP/port for media, directionality.',
    whyExists: 'Two endpoints must agree on how the audio will be encoded and where it will be sent, before any of it flows.',
    problemSolved: 'Codec and transport negotiation in one round trip.',
    whereInVoice: 'Every call setup, phone or browser. Reading SDP is the first skill of media debugging.',
    alternatives: [],
    limitations: ['Verbose, order-sensitive, easy to mangle in middleboxes'],
    scaling: 'N/A (a few KB per call setup).',
    failureModes: ['No common codec → call fails or transcodes', 'private IPs in SDP → one-way audio'],
    related: ['sip', 'webrtc', 'codecs'],
  }),
  c({
    id: 'sip-trunking', term: 'SIP trunking', category: 'telephony',
    whatIsIt: 'Buying carrier connectivity as SIP sessions to your own equipment (SBC) instead of physical phone lines or a full CPaaS.',
    whyExists: 'The middle path between renting everything (CPaaS) and being a carrier: wholesale minutes with your own call control.',
    problemSolved: 'Roughly half-price per-minute costs (assumption) and full control of media and routing.',
    whereInVoice: 'The telephony edge for cost-sensitive, high-volume deployments; the simulator\'s decision engine switches to it at scale + low-cost posture.',
    alternatives: ['CPaaS (rented simplicity)', 'hybrid: CPaaS numbers with BYOC trunks'],
    limitations: ['You operate SBCs, monitor carriers, debug DTMF and one-way audio', 'channel capacity is a contract ceiling'],
    scaling: 'Add trunks/carriers; multi-carrier routing becomes your job.',
    failureModes: ['Trunk registration loss = total phone outage', 'carrier route quality shifting under you'],
    related: ['sip', 'pstn'],
  }),
  c({
    id: 'dtmf', term: 'DTMF', category: 'telephony',
    whatIsIt: 'Touch-tone digits ("press 1 for..."), carried in-band as tones or out-of-band as RTP events / SIP INFO.',
    whyExists: 'Predates speech recognition; still the most reliable input on a bad line.',
    problemSolved: 'Deterministic input for menus, PINs and confirmation when STT cannot be trusted.',
    whereInVoice: 'Fallback input ("or press 1"), secure digit entry, IVR interop. A robust agent handles both speech and digits.',
    alternatives: ['Speech-only (fails on noisy lines and privacy-sensitive digits)'],
    limitations: ['In-band tones can garble through lossy codecs — RFC 2833/4733 out-of-band events exist for this reason'],
    scaling: 'Negligible compute and bandwidth; it scales with your telephony tier. The real cost is design: every prompt needs both a spoken and a keypad path, and both need testing.',
    failureModes: ['Double-digit detection from echo', 'in-band tones destroyed by transcoding'],
    related: ['pstn', 'sip'],
  }),

  c({
    id: 'media-plane', term: 'Media plane vs control plane', category: 'networking',
    whatIsIt:
      'The split between the path that carries audio (media plane: RTP/SRTP/WebSocket frames, STT, TTS, the gateway) and the path that carries state, routing, configuration and telemetry (control plane: SIP signalling, session state, CRM, billing, monitoring).',
    whyExists:
      'The two have irreconcilable requirements. Media is latency-critical, high-volume and worthless when late — a 200 ms-old audio frame is garbage. Control is correctness-critical, low-volume and can afford to retry. Building both to the stricter standard is wasteful; building both to the looser one produces stuttering audio.',
    problemSolved:
      'It gives you a rule for every component: if it is on the media plane it must never block, never do disk I/O, and never wait on a slow dependency. If it is on the control plane it may be slow — but it must never be in a position to stall media.',
    whereInVoice:
      'Telephony invented it: SIP sets calls up while RTP carries the voice on a separate path, which is why an established call keeps talking when a SIP proxy dies. The same split governs modern designs — the media gateway and STT/TTS are media plane; Redis, Postgres, queues, CRM and monitoring are control plane. This simulator colour-codes every connection by plane for exactly this reason.',
    alternatives: ['Ignoring the distinction — which works until the first database hiccup makes every caller hear stuttering audio'],
    limitations: [
      'The boundary needs policing: a well-meaning "just one quick lookup" inside the audio loop is how the rule gets broken',
      'Some components legitimately straddle both (the agent runtime consumes media-plane transcripts and writes control-plane state) and need internal discipline',
    ],
    scaling:
      'The two planes scale on different axes: media by concurrent connections, bandwidth and CPU; control by requests/sec and storage. Separating them lets you scale (and fail) them independently — and lets you size a big media tier without a proportionally big database.',
    failureModes: [
      'Control-plane latency leaking into the media path (a DB query inside an audio callback) → audio deadline misses on every call on that box',
      'Control-plane outage taken as total outage because state was never made optional for in-flight calls',
      'Synchronous telemetry or CRM writes from the media loop — the classic "our monitoring took down production" incident',
    ],
    related: ['rtp', 'sip', 'backpressure', 'session-state', 'observability'],
  }),

  // ======================================================================
  // AI
  // ======================================================================
  c({
    id: 'stt', term: 'Speech-to-text (STT/ASR)', category: 'ai',
    whatIsIt: 'Models that turn audio into text; streaming engines emit revisable partial hypotheses in real time, batch engines transcribe completed audio.',
    whyExists: 'The reasoning layer (LLM) reads text; someone must cross the audio–text boundary fast and accurately.',
    problemSolved: 'The agent\'s hearing.',
    whereInVoice: 'On the media path, fed PCM by the gateway; its partials drive endpointing and its finals feed the LLM.',
    alternatives: ['Speech-to-speech models (no separate STT)', 'DTMF menus (the ancestors)'],
    limitations: ['Accuracy drops with 8 kHz audio, noise, accents and code-switching', 'streaming partials revise themselves — consumers must handle instability'],
    scaling: 'One held stream per live call: provider concurrency quotas (managed) or GPU streams (self-hosted) are the ceiling.',
    failureModes: ['Provider outage = deaf agent (fallback provider!)', 'silent accuracy degradation caught only by confidence/complaint trends'],
    related: ['streaming', 'vad', 'sample-rate'],
    keyNumbers: [{ label: 'Streaming first partial', value: '~200–400 ms', note: 'simulation assumption' }],
  }),
  c({
    id: 'tts', term: 'Text-to-speech (TTS)', category: 'ai',
    whatIsIt: 'Models that turn text into audio; streaming engines emit the first chunk in ~100–300 ms while the rest generates.',
    whyExists: 'The agent must speak; voice quality and time-to-first-audio are both product features.',
    problemSolved: 'The agent\'s voice — and, streamed sentence-by-sentence, the illusion of instant thought.',
    whereInVoice: 'Fed sentences by the runtime as LLM tokens arrive; its chunks flow back through the gateway to the caller.',
    alternatives: ['Recorded prompts (IVR era)', 'S2S models (voice included)'],
    limitations: ['Premium voices cost real money per character', 'non-streaming APIs (file-per-request) are unusable on live paths'],
    scaling: 'Held streams and characters/minute quotas; caching common phrases is the classic optimisation.',
    failureModes: ['Outage = mute agent (the fallback-voice pattern exists for this)', 'mid-utterance underruns when generation lags playback'],
    related: ['streaming', 'llm', 'codecs'],
    keyNumbers: [{ label: 'Streaming first audio', value: '~100–300 ms', note: 'simulation assumption' }],
  }),
  c({
    id: 'llm', term: 'Large language model', category: 'ai',
    whatIsIt: 'The reasoning engine: reads the conversation, produces the reply and/or structured tool calls, streamed token by token.',
    whyExists: 'Scripted dialog trees could not handle open human speech; LLMs made general conversation tractable.',
    problemSolved: 'Understanding intent, deciding actions, and phrasing answers — the agent\'s mind.',
    whereInVoice: 'Called by the runtime once per turn (sometimes twice, around a tool call). Its time-to-first-token sits squarely in the perceived-latency budget.',
    alternatives: ['Intent classifiers + templates (fast, rigid)', 'S2S models (LLM fused with audio)'],
    limitations: ['Tail latency (p99 ≫ p50)', 'context size taxes every turn in latency and money', 'occasional malformed tool calls — validate everything'],
    scaling: 'Tokens/minute and requests/minute quotas; self-hosting trades quota for GPU fleet operations.',
    failureModes: ['Timeout = awkward silence (budget + filler + retry)', 'quality drift across model versions — regression-test prompts'],
    related: ['function-calling', 'streaming', 'memory'],
    keyNumbers: [
      { label: 'Fast-model TTFT', value: '~200 ms', note: 'simulation assumption' },
      { label: 'Flagship TTFT', value: '~650 ms', note: 'simulation assumption — audible in conversation' },
    ],
  }),
  c({
    id: 's2s', term: 'Speech-to-speech models', category: 'ai',
    whatIsIt: 'Realtime models that consume audio and produce audio directly — STT, LLM and TTS fused into one provider session with native turn taking.',
    whyExists: 'Composed pipelines pay latency and lose prosody at every boundary; a single model avoids both.',
    problemSolved: 'The most natural-feeling conversations currently possible: fast, expressive, native barge-in.',
    whereInVoice: 'Replaces the STT→LLM→TTS core; your side becomes transport + tools + state.',
    alternatives: ['Composed streaming pipeline (control, auditability, per-piece vendors)'],
    limitations: ['One-vendor lock-in of the entire voice', 'weak transcript visibility', 'per-minute session pricing that runs during silence'],
    scaling: 'Provider session quotas; your infrastructure thins to a relay.',
    failureModes: ['Provider outage takes hearing, thinking and speaking simultaneously — keep a composed pipeline warm as fallback'],
    related: ['llm', 'stt', 'tts', 'turn-detection'],
  }),
  c({
    id: 'vad', term: 'Voice activity detection', category: 'ai',
    whatIsIt: 'A tiny model classifying each ~30 ms audio window as speech or not-speech, within a few milliseconds.',
    whyExists: 'The system needs sub-50 ms awareness of "the user is talking" — far faster than STT can confirm it.',
    problemSolved: 'The reflexes: barge-in detection and the raw signal endpointing is built on.',
    whereInVoice: 'In-process on the media gateway, watching every frame.',
    alternatives: ['Energy gates (fooled by noise)', 'STT-driven detection (too slow for barge-in)'],
    limitations: ['Knows sound, not meaning: silence ≠ finished thought', 'thresholds need tuning on real production audio'],
    scaling: '~1% CPU per call (assumption); scales with the gateway.',
    failureModes: ['Too sensitive → phantom interruptions', 'too lax → missed barge-ins and slow endpoints'],
    related: ['turn-detection', 'barge-in', 'stt'],
  }),
  c({
    id: 'turn-detection', term: 'Turn detection / endpointing', category: 'ai',
    whatIsIt: 'Deciding the user has finished their thought — VAD silence timers, STT end-of-utterance signals, and increasingly semantic models reading the partial transcript.',
    whyExists: '"Stopped making sound" and "finished the thought" are different facts; answering on the wrong one interrupts people mid-idea.',
    problemSolved: 'When to commit the turn — the single largest tunable term in perceived latency.',
    whereInVoice: 'Runtime logic fed by VAD + STT; the silence-timeout knob every voice team ends up arguing about.',
    alternatives: ['Push-to-talk (walkie-talkie UX)', 'native S2S turn taking'],
    limitations: ['Pure silence timers force an eager-vs-polite tradeoff with no right answer', 'semantic endpointing adds its own model latency'],
    scaling: 'Negligible compute; enormous UX leverage.',
    failureModes: ['Premature commit → interrupting; late commit → the agent feels slow. Both are this one knob.'],
    related: ['vad', 'barge-in', 'latency-perception'],
    keyNumbers: [{ label: 'Typical silence timeout', value: '300–800 ms', note: '600 ms simulation default' }],
  }),
  c({
    id: 'barge-in', term: 'Barge-in / interruption', category: 'ai',
    whatIsIt: 'The user speaking while the agent speaks — and the machinery to stop the agent instantly: cancel TTS, flush buffers, open a new turn.',
    whyExists: 'Humans interrupt constantly; an agent that ploughs on is unusable regardless of its intelligence.',
    problemSolved: 'Conversational give-and-take.',
    whereInVoice: 'A media-plane reflex (VAD + min-duration gate) triggering control-plane cleanup (cancel, flush, state transition).',
    alternatives: ['Half-duplex push-to-talk (dodges the problem, feels like a radio)'],
    limitations: ['Speakerphone echo can self-trigger it (AEC required)', 'the flush step is the one everyone forgets'],
    scaling: 'N/A — correctness, not capacity.',
    failureModes: ['Cancelled TTS but unflushed transport buffer → agent "talks over" the user for seconds: the classic bug, reproduced in the VAD Lab'],
    related: ['vad', 'turn-detection', 'state-machines'],
  }),
  c({
    id: 'streaming', term: 'Streaming (pipeline principle)', category: 'ai',
    whatIsIt: 'Processing data as it arrives instead of after it completes: STT partials during speech, LLM tokens during generation, TTS chunks during synthesis.',
    whyExists: 'Serial completion is arithmetic death for latency: sum(all stages) vs max(overlapped critical path).',
    problemSolved: 'Sub-second perceived latency from stages that individually take longer than a second combined.',
    whereInVoice: 'The defining property of every modern voice pipeline; the Latency Lab quantifies it stage by stage.',
    alternatives: ['Batch everything (simpler; 2–4 s slower, simulation estimate)'],
    limitations: ['Partial results revise themselves', 'cancellation and cleanup are your problem', 'debugging needs tracing, not print statements'],
    scaling: 'Streams hold connections open — capacity is counted in concurrent streams.',
    failureModes: ['Consuming partials as finals', 'sentence-chunking errors feeding TTS half-thoughts'],
    related: ['stt', 'tts', 'llm', 'latency-perception'],
  }),
  c({
    id: 'latency-perception', term: 'Latency perception', category: 'ai',
    whatIsIt: 'How response delay feels: <500 ms sharp, ~800 ms natural, 1.5 s sluggish, 3 s broken (rules of thumb, simulation assumptions).',
    whyExists: 'Human turn-taking gaps average ~200 ms; deviations register as social signals (hesitation, inattention) before users can name them.',
    problemSolved: 'Gives every technical budget its meaning: the number to hit is perceptual, not technical.',
    whereInVoice: 'The north-star metric: measured from end of user speech to first agent audio.',
    alternatives: [],
    limitations: ['Fillers ("hmm, let me check") buy time but spend trust if overused'],
    scaling: 'It does not scale — it is a constant the system must meet at every load level. That is what makes it the honest SLO: p95 perceived latency measured at peak, not at 3 am.',
    failureModes: ['Optimising mean while p95 ruins every twentieth turn — tails are the product'],
    related: ['streaming', 'turn-detection', 'observability'],
  }),

  // ======================================================================
  // AGENT SYSTEMS
  // ======================================================================
  c({
    id: 'function-calling', term: 'Function calling / tools', category: 'agents',
    whatIsIt: 'The LLM emitting structured calls ({name, arguments}) against a declared schema; the runtime validates, executes and returns results for phrasing.',
    whyExists: 'Talking is not doing: real tasks need lookups, bookings and payments against real systems.',
    problemSolved: 'A typed, auditable boundary between probabilistic language and deterministic systems.',
    whereInVoice: 'Mid-turn, inside the latency budget: blocking reads must fit ~1.5 s with filler; writes go async.',
    alternatives: ['Intent + slot filling (rigid)', 'freeform text parsing (fragile)'],
    limitations: ['Models emit malformed or misjudged calls — validate and confirm consequential actions aloud', 'every tool result re-enters the context (latency + cost)'],
    scaling: 'AI concurrency multiplies backend load beyond anything human agents produced; capacity-test the tools.',
    failureModes: ['Slow tool = dead air (timeout + filler)', 'retried writes double-booking (idempotency keys — see this repo\'s handlers)'],
    related: ['llm', 'idempotency', 'timeout-budgets'],
  }),
  c({
    id: 'state-machines', term: 'Conversation state machines', category: 'agents',
    whatIsIt: 'Explicit states (LISTENING, PROCESSING, SPEAKING, INTERRUPTED…) with a transition table saying which events mean what, when.',
    whyExists: 'The same event means different things in different moments; implicit state in scattered booleans becomes unmaintainable immediately.',
    problemSolved: 'Predictable behaviour under weird event orderings — transcripts after hangups, barge-ins during tool calls.',
    whereInVoice: 'The heart of the agent runtime; the State Machine Lab renders the exact machines this simulator runs.',
    alternatives: ['Event-soup ad-hoc handling (every voice team\'s first architecture, briefly)'],
    limitations: ['State explosion if modelled too finely — machines per concern (conversation, telephony, handoff) beat one giant machine'],
    scaling: 'N/A — correctness infrastructure.',
    failureModes: ['Missing transitions → wedged calls (watchdog timers per state are the safety net)'],
    related: ['barge-in', 'human-handoff', 'session-state'],
  }),
  c({
    id: 'memory', term: 'Memory & context', category: 'agents',
    whatIsIt: 'What the agent knows: this-turn context (prompt), this-call state (session store), and across-calls memory (CRM/profile).',
    whyExists: 'LLMs are stateless functions; every scrap of continuity must be engineered in.',
    problemSolved: 'Coherent conversations ("as I said, the 15th") and continuity across calls ("welcome back").',
    whereInVoice: 'The context builder assembles each prompt from all three layers — under a token budget, because context is a per-turn latency and cost tax.',
    alternatives: [],
    limitations: ['Long calls force summarisation (lossy)', 'cross-call memory raises privacy/retention questions to answer explicitly'],
    scaling: 'Session state sizes Redis; profiles size Postgres; token budgets size your LLM bill.',
    failureModes: ['Context bloat (slow + expensive)', 'stale memory confidently asserted'],
    related: ['session-state', 'llm', 'rag'],
  }),
  c({
    id: 'rag', term: 'RAG (Retrieval-Augmented Generation)', category: 'agents',
    whatIsIt: 'Retrieving relevant documents (policies, FAQs, account data) per turn and injecting them into the prompt, instead of hoping the model memorised them.',
    whyExists: 'Models cannot know your current refund policy; retraining per policy change is absurd.',
    problemSolved: 'Grounded, current, citable answers from your own knowledge.',
    whereInVoice: 'A retrieval step inside PROCESSING — its latency (typically 50–300 ms, assumption) sits in the turn budget like any tool.',
    alternatives: ['Fine-tuning (slow to update)', 'stuffing everything into the prompt (token explosion)'],
    limitations: ['Retrieval quality caps answer quality', 'chunking and freshness pipelines are real engineering'],
    scaling: 'A vector/search dependency with its own capacity and failure story.',
    failureModes: ['Wrong retrieval → confident wrong answers', 'retriever down → degrade to general answers with a disclaimer, not silence'],
    related: ['memory', 'llm', 'function-calling'],
  }),

  // ======================================================================
  // INFRASTRUCTURE
  // ======================================================================
  c({
    id: 'redis', term: 'Redis', category: 'infrastructure',
    whatIsIt: 'An in-memory data store serving reads/writes in ~100 µs: hashes, sorted sets, TTLs, pub/sub, locks.',
    whyExists: 'Some state is too hot for disk databases and too important for process memory.',
    problemSolved: 'Session state that survives server death and is fast enough to touch every turn.',
    whereInVoice: 'The conversation\'s external brain: written at turn boundaries, read on reconnect/adoption, TTL-guarded.',
    alternatives: ['Process memory (dies with the process)', 'Postgres (10–50× slower, connection-hungry)', 'Memcached (no structures)'],
    limitations: ['RAM-priced capacity', 'failover takes seconds — decide beforehand what live calls do during them'],
    scaling: 'Replicas for reads, cluster sharding for writes/memory; hot keys defeat sharding.',
    failureModes: ['Eviction storms deleting live sessions (TTL hygiene, noeviction for session data)', 'putting it on the per-frame path (never)'],
    related: ['session-state', 'postgres', 'memory'],
  }),
  c({
    id: 'postgres', term: 'PostgreSQL', category: 'infrastructure',
    whatIsIt: 'The default relational database: transactions, constraints, SQL, replication.',
    whyExists: 'Durable facts with invariants (a slot booked once) need a store that enforces them.',
    problemSolved: 'The system of record: bookings, customers, call outcomes, audit.',
    whereInVoice: 'Strictly control-plane: tools read it (pooled, timed-out), the queue writes it. Never on the media path — the validator enforces this.',
    alternatives: ['MySQL (equivalent)', 'KV stores (scale before semantics)', 'managed Postgres e.g. Supabase — what this repo uses'],
    limitations: ['Write scaling is vertical until sharding', 'connections are precious: voice concurrency demands a pooler'],
    scaling: 'Read replicas + cache first; shard last.',
    failureModes: ['Pool exhaustion under call concurrency (the classic voice-scale incident)', 'slow query inside a live turn = dead air'],
    related: ['redis', 'idempotency', 'queues'],
  }),
  c({
    id: 'kafka', term: 'Kafka / event logs', category: 'infrastructure',
    whatIsIt: 'A partitioned, durable, replayable append-only log consumed independently by many systems.',
    whyExists: 'When analytics, billing, QA and ML all want the event stream, point-to-point queues become spaghetti.',
    problemSolved: 'One durable truth of what happened, consumed at each reader\'s own pace, replayable.',
    whereInVoice: 'The analytical spine at scale: call events, transcript fragments, metrics flow through it — never synchronously from the media path.',
    alternatives: ['Simple queues (tasks, not history)', 'Postgres outbox (honest small-scale answer)'],
    limitations: ['Real operational weight', 'partition count is awkward to change later'],
    scaling: 'Partitions set consumer parallelism; brokers scale horizontally.',
    failureModes: ['Consumer lag (alert on age, not count)', 'synchronous produce from the call path stalling turns (fire-and-forget only)'],
    related: ['queues', 'observability'],
  }),
  c({
    id: 'queues', term: 'Message queues', category: 'infrastructure',
    whatIsIt: 'Buffered task hand-off: producers enqueue, consumers process and ack, failures redeliver.',
    whyExists: 'Slow, bursty, retryable work must not run inside a live conversation.',
    problemSolved: 'Absorbs spikes and isolates the real-time path from every side effect (CRM writes, uploads, notifications).',
    whereInVoice: 'Between the runtime and everything that can wait: the async/sync sort is a core architectural act.',
    alternatives: ['Kafka (when replay/many-readers matter)', 'in-DB job tables (small scale)'],
    limitations: ['At-least-once delivery ⇒ consumers must be idempotent', 'eventual consistency for side effects'],
    scaling: 'Consumers scale on queue depth — the most honest load signal in the system.',
    failureModes: ['Unbounded growth when consumers die (dead-letter queues, alerts on oldest-age)', 'poison messages looping forever'],
    related: ['backpressure', 'idempotency', 'kafka'],
  }),
  c({
    id: 'kubernetes', term: 'Kubernetes', category: 'infrastructure',
    whatIsIt: 'Declarative container orchestration: you state desired replicas/resources; controllers reconcile reality.',
    whyExists: 'Humans cannot place, heal and roll fleets by hand past a handful of servers.',
    problemSolved: 'Autoscaling, self-healing, controlled rollouts as configuration.',
    whereInVoice: 'Runs the fleet — with voice-specific settings: long termination grace (calls last minutes), guaranteed CPU for media pods, disruption budgets.',
    alternatives: ['VMs + systemd (simpler, static)', 'managed container runtimes'],
    limitations: ['Complexity tax', 'defaults are web-shaped: 30 s grace periods kill 15-minute calls'],
    scaling: 'HPA on connection metrics (CPU lags); scale-up must cover image-pull + warmup lead time.',
    failureModes: ['Deploys dropping live calls (drain hooks!)', 'bin-packing media pods into CPU throttling'],
    related: ['autoscaling', 'connection-draining', 'load-balancing'],
  }),
  c({
    id: 'load-balancing', term: 'Load balancing', category: 'infrastructure',
    whatIsIt: 'Distributing connections across replicas with health checks ejecting dead backends.',
    whyExists: 'More load than one box, and no single box you can afford to lose.',
    problemSolved: 'Placement and failover for the fleet.',
    whereInVoice: 'Placement is decided once per call (connect time) and lasts minutes — so the policy (least-connections) matters far more than for web requests, and idle timeouts must exceed call lengths.',
    alternatives: ['DNS round robin (slow failover)', 'connection brokers (clients ask, then connect direct)'],
    limitations: ['Cannot rebalance live calls without dropping them', 'long-call skew accumulates across the fleet'],
    scaling: 'Managed LBs scale themselves; watch connection tables and per-backend skew.',
    failureModes: ['Idle timeout killing quiet calls at a suspiciously round duration', 'health-check flapping causing reconnect storms'],
    related: ['websocket', 'connection-draining', 'autoscaling'],
  }),
  c({
    id: 'autoscaling', term: 'Autoscaling', category: 'infrastructure',
    whatIsIt: 'Adding/removing capacity automatically from metrics: target utilisation, warmup lag, scale-in delays.',
    whyExists: 'Voice traffic is spiky and capacity is money; static fleets are either wasteful or insufficient.',
    problemSolved: 'Capacity that follows demand — with the physics of warmup lag made explicit.',
    whereInVoice: 'The media tier: scale OUT on connections/arrival rate (CPU lags), scale IN only by draining (calls cannot be evicted). The Scaling Lab simulates exactly this.',
    alternatives: ['Static peak-sized fleets (simple, pay for 3 am capacity)', 'scheduled scaling (good for known diurnal shapes)'],
    limitations: ['New instances take 1–3 min to serve (assumption): spikes faster than that need standing headroom'],
    scaling: 'It IS scaling; its own limits are quota ceilings and warmup lead time.',
    failureModes: ['Scaling on CPU alone (lags accepted connections)', 'aggressive scale-in dropping live calls', 'flapping'],
    related: ['kubernetes', 'load-balancing', 'connection-draining'],
  }),
  c({
    id: 'connection-draining', term: 'Connection draining', category: 'infrastructure',
    whatIsIt: 'Removing a server gracefully: stop accepting new connections, let existing ones finish, then terminate.',
    whyExists: 'Voice connections last minutes and cannot move; killing a server kills its calls.',
    problemSolved: 'Zero-drop deploys and scale-ins.',
    whereInVoice: 'Every deploy of every connection-holding tier; grace periods must exceed the longest supported call.',
    alternatives: ['Session migration (serialise and adopt mid-call state — complex, rare)', 'accepting drops in a window (honest for internal tools)'],
    limitations: ['Deploys take up to a call-length', 'drains + autoscale-in interact trickily'],
    scaling: 'N/A — an operational discipline.',
    failureModes: ['The default 30 s grace period vs the 15-minute call: the classic voice deploy incident'],
    related: ['kubernetes', 'load-balancing', 'websocket'],
  }),
  c({
    id: 'session-state', term: 'Session state ownership', category: 'infrastructure',
    whatIsIt: 'The explicit decision of where each piece of live-call state lives (process, Redis, DB) and who may write it.',
    whyExists: 'Unowned state gets duplicated, dropped and fought over; every voice bug archaeology ends at ambiguous state.',
    problemSolved: 'Crash recovery, reconnect-with-context, zero-downtime deploys.',
    whereInVoice: 'Turn-boundary writes to Redis; durable outcomes to Postgres via the queue; process memory only for what may die with the process.',
    alternatives: [],
    limitations: ['Turn-boundary granularity loses the last partial turn on crash — an explicit, accepted trade'],
    scaling: 'Defines what Redis must hold: peak concurrent sessions × per-session bytes.',
    failureModes: ['State in two places disagreeing', 'sessions never expiring (TTL hygiene)'],
    related: ['redis', 'state-machines', 'memory'],
  }),
  c({
    id: 'human-handoff', term: 'Human handoff', category: 'infrastructure',
    whatIsIt: 'Escalating a live AI call to a person: availability routing, queueing, media re-anchor, context transfer — a distributed transaction, not a phone feature.',
    whyExists: 'Every AI has an edge; customers find it while angry, and regulation sometimes requires a human anyway.',
    problemSolved: 'Graceful escalation with no repeated explanations and no dead-end transfers.',
    whereInVoice: 'The TRANSFERRING branch of the telephony state machine; the Handoff Lab plays every branch including the failures.',
    alternatives: ['Callback scheduling', 'voicemail + ticket', 'never (until the first viral complaint)'],
    limitations: ['Humans are ~50× the per-minute cost (assumption) and scale by hiring (Erlang math)', 'context transfer requires desktop integration work'],
    scaling: 'Staffing curves, not autoscaling; queue theory says 80% occupancy ≈ double the wait of 70%.',
    failureModes: ['No-agent dead ends (design the fallback branch)', 'context lost → “can you repeat all that?”'],
    related: ['state-machines', 'queues'],
  }),

  // ======================================================================
  // RELIABILITY
  // ======================================================================
  c({
    id: 'retry', term: 'Retries', category: 'reliability',
    whatIsIt: 'Attempting a failed operation again — with a budget, with backoff, and only when safe.',
    whyExists: 'Much failure is transient: a blip, a restarted pod, a dropped packet.',
    problemSolved: 'Converts transient noise into invisible recovery.',
    whereInVoice: 'Compressed by the latency budget: one fast retry, then fallback. The polite exponential schedule belongs to batch jobs, not live turns.',
    alternatives: ['Fail fast to a fallback (often better mid-call)'],
    limitations: ['Retrying non-idempotent writes double-books', 'synchronized retries stampede a recovering service (jitter!)'],
    scaling: 'Retry amplification: at 90% provider failure, 3 attempts ≈ 3× load exactly when the provider is dying — pair with a circuit breaker.',
    failureModes: ['Retry storms', 'burning the whole turn budget on a doomed endpoint'],
    related: ['timeout-budgets', 'circuit-breaker', 'idempotency'],
  }),
  c({
    id: 'timeout-budgets', term: 'Timeouts & budgets', category: 'reliability',
    whatIsIt: 'A deadline on every external call, derived from what the caller can tolerate, with a defined behaviour when it fires.',
    whyExists: 'Without a timeout, a hung dependency hangs the conversation forever while resources leak.',
    problemSolved: 'Bounded worst-case behaviour: the difference between "slow" and "wedged".',
    whereInVoice: 'Budgets cascade: 800 ms perceived ⇒ ~4 s LLM abort, ~1.5 s tool budget, filler at ~900 ms. The validator flags missing and un-affordable timeouts alike.',
    alternatives: [],
    limitations: ['A timeout you cannot afford to wait for is not protection — budgets must fit the conversation'],
    scaling: 'Budgets tighten as you scale, not loosen: queueing delay at high utilisation eats the same budget, so a timeout comfortable at 10 concurrent calls can be the thing firing constantly at 1,000.',
    failureModes: ['30 s library defaults inside a 1 s conversational moment', 'timeout with no follow-up action (what does the caller HEAR?)'],
    related: ['retry', 'fallback', 'function-calling'],
  }),
  c({
    id: 'circuit-breaker', term: 'Circuit breakers', category: 'reliability',
    whatIsIt: 'A failure-rate switch: too many recent failures opens it (calls fail fast / go to fallback); after a cooldown, a probe decides whether to close.',
    whyExists: 'Retrying into a dead provider wastes the caller\'s time and kicks the provider while it is down.',
    problemSolved: 'Fast failure during outages, automatic recovery after, load relief for the struggling dependency.',
    whereInVoice: 'Around every external provider; open-breaker = instant fallback voice/STT instead of a timeout burn per call. The Reliability Lab shows the p95 difference.',
    alternatives: ['Health-check-driven routing (proactive, can lag reality)'],
    limitations: ['Thresholds need tuning: hair-triggers flap, numb ones never trip'],
    scaling: 'Per-provider per-instance state; trivial.',
    failureModes: ['Flapping on marginal providers', 'shared breaker hiding per-region partial failures'],
    related: ['retry', 'fallback', 'timeout-budgets'],
  }),
  c({
    id: 'fallback', term: 'Fallbacks & graceful degradation', category: 'reliability',
    whatIsIt: 'A pre-arranged worse-but-working alternative: second TTS vendor, cheaper LLM, cached answer, callback offer.',
    whyExists: 'Availability math: a single 99.9% dependency caps you at 99.9%; independent fallbacks multiply the nines.',
    problemSolved: 'Outages become degradations the caller barely notices instead of failures they report.',
    whereInVoice: 'Per stage: fallback STT (worse accuracy), fallback TTS (different voice), scripted responses (no LLM), callback (no humans). Voice adds a twist: the caller HEARS the degradation — script it.',
    alternatives: ['Honest apology + hangup (a valid, explicit choice at low tiers)'],
    limitations: ['Untested fallbacks fail when finally used — rehearse them in the Chaos Lab equivalent of production', 'double the integration surface'],
    scaling: 'Fallback capacity must exist when primary dies: cold fallbacks are fiction.',
    failureModes: ['Fallback provider quota too small for failover load', 'silent quality drift on the fallback path'],
    related: ['circuit-breaker', 'retry', 'human-handoff'],
  }),
  c({
    id: 'idempotency', term: 'Idempotency', category: 'reliability',
    whatIsIt: 'Designing operations so doing them twice equals doing them once — usually via a caller-supplied key the backend deduplicates on.',
    whyExists: 'Retries, webhook redeliveries and network ambiguity guarantee duplicates; only the backend can make them safe.',
    problemSolved: 'Retry-safety for writes: no double bookings, no double charges.',
    whereInVoice: 'Every tool that writes. This repository derives a key from (call, slot, customer) and enforces uniqueness in Postgres — the exact production pattern.',
    alternatives: ['Exactly-once delivery (a myth at the boundaries that matter)'],
    limitations: ['Key scope needs thought: same-call retry must collide, tomorrow\'s identical request must not'],
    scaling: 'A unique index and a conflict branch; nearly free.',
    failureModes: ['Keys from unstable inputs (timestamps!)', 'dedup table without TTL growing forever'],
    related: ['retry', 'queues', 'function-calling'],
  }),

  c({
    id: 'recording', term: 'Call recording', category: 'infrastructure',
    whatIsIt:
      'Forking the live media stream to a durable copy of the conversation — usually one compressed file per call (plus, increasingly, the transcript alongside it).',
    whyExists:
      'Quality assurance, dispute resolution, agent coaching, model training and — in several industries — a regulatory requirement to retain what was said.',
    problemSolved: 'Gives you the evidence of what actually happened on a call, which no amount of metrics can reconstruct.',
    whereInVoice:
      'A fork at the media gateway into a bounded local buffer, then an asynchronous upload to object storage via the queue. The fork must never be inline with the live path: an upload stall must not become audio latency.',
    alternatives: [
      'Provider-side recording (simplest when you use a CPaaS — take it if offered)',
      'Transcript-only retention (far cheaper and less sensitive, but loses tone and disputes over wording)',
    ],
    limitations: [
      'Consent and notification rules vary by jurisdiction and are a legal question, not an engineering one',
      'Recordings are among the most sensitive data you hold — encryption, access audit and deletion all become real work',
      'Storing raw PCM instead of a compressed codec costs roughly 10× for no review-grade benefit',
    ],
    scaling:
      'Volume × duration × bitrate × retention. 10k calls/day at 4 min and ~0.7 MB/min is ~28 GB/day — about 840 GB accumulating per month of retention. Lifecycle rules to cold storage are a budget lever, not an optimisation.',
    failureModes: [
      'Synchronous upload on call teardown → calls that "never end" in your metrics and leaked resources',
      'Local disk fills because the async uploader fell behind and nobody alerted on the buffer',
      'Recordings kept forever because the retention default was never set — a growing cost and a growing liability',
    ],
    related: ['data-retention', 'queues', 'media-plane', 'security-pii'],
    keyNumbers: [{ label: 'Compressed call audio', value: '~0.7 MB/min', note: 'Opus-class assumption; raw PCM is ~10× more' }],
  }),
  c({
    id: 'data-retention', term: 'Data retention (educational)', category: 'security',
    whatIsIt:
      'The policy — and the machinery that enforces it — deciding how long recordings, transcripts, logs and derived data live before they are provably deleted. Educational architecture considerations, not legal advice.',
    whyExists:
      'Data you no longer need is pure liability: it costs storage, widens breach impact, and in regulated contexts its continued existence can itself be the violation.',
    problemSolved: 'Turns "how long do we keep this?" from an unanswered default into an enforced, auditable property of the system.',
    whereInVoice:
      'Object-storage lifecycle rules for recordings, TTL on Redis session keys, partition-drop policies for transcript tables, and log retention in the observability stack — four separate systems that must agree on one policy.',
    alternatives: ['Keeping everything forever (a decision, usually an unexamined one)', 'Aggressive minimisation: store transcripts, discard audio'],
    limitations: [
      'Deletion must be provable, including from backups and replicas — the hard part',
      'Retention interacts with legal hold, which must be able to override the automation',
      'Derived data (embeddings, fine-tuning sets) can outlive the source it was derived from unless explicitly tracked',
    ],
    scaling:
      'Steady-state storage equals ingest rate × retention period, so retention is a direct multiplier on cost. Deletion throughput itself becomes a workload at high volume.',
    failureModes: [
      'Lifecycle rules configured on the bucket but not on replicas or backups',
      'Cron-script deletion that silently stops working and is noticed at audit time',
      'PII inside logs and traces, which nobody remembered were also retained data',
    ],
    related: ['recording', 'security-pii', 'observability'],
  }),

  // ======================================================================
  // OBSERVABILITY & SECURITY
  // ======================================================================
  c({
    id: 'observability', term: 'Observability (logs, metrics, traces)', category: 'observability',
    whatIsIt: 'Structured logs (events with context), metrics (numbers over time), traces (per-request span trees) — three views of one system.',
    whyExists: '"The agent feels slow" is not debuggable; per-stage latency histograms are.',
    problemSolved: 'Diagnosis, alerting, capacity planning, SLO accounting.',
    whereInVoice: 'call_id on every log line (this repo does this), a span per pipeline stage per turn, and the perceived-latency histogram as the north-star chart. The event timeline in this simulator IS the trace view to aspire to.',
    alternatives: [],
    limitations: ['Cardinality costs money: per-call-id metrics explode; keep IDs in logs/traces, aggregates in metrics'],
    scaling: 'Telemetry volume scales with calls × verbosity; sample traces, never sample errors.',
    failureModes: ['Blocking the app on telemetry (never)', 'dashboards nobody rehearsed reading during an incident'],
    related: ['opentelemetry', 'latency-perception', 'rtcp'],
  }),
  c({
    id: 'opentelemetry', term: 'OpenTelemetry', category: 'observability',
    whatIsIt: 'The vendor-neutral standard for emitting traces, metrics and logs: one instrumentation, any backend.',
    whyExists: 'Instrumentation was vendor-locked; OTel decoupled the emitting from the storing.',
    problemSolved: 'Portable telemetry and, crucially, context propagation — the trace id follows the call through gateway, runtime and providers.',
    whereInVoice: 'Spans per stage per turn with call_id/turn_id attributes; the collector fans out to whatever backend.',
    alternatives: ['Vendor SDKs (lock-in)', 'bare structured logs (no causality)'],
    limitations: ['Streaming/audio spans need conventions of your own (when does an "STT span" end?)'],
    scaling: 'Collector as a buffer/sampler between your fleet and your bill.',
    failureModes: ['Broken context propagation → orphan spans → no story per call'],
    related: ['observability'],
  }),
  c({
    id: 'security-pii', term: 'Security & PII in voice (educational)', category: 'security',
    whatIsIt: 'The sensitive-data surface of a voice platform: live audio, transcripts, recordings, CRM context — flowing through more systems than any web form. Educational architecture considerations, not legal or compliance advice.',
    whyExists: 'Voice systems inherently process personal data, often payment/health adjacent, across many vendors.',
    problemSolved: 'Thinking about it at design time: where data flows, who sees it, how long it lives.',
    whereInVoice: 'Encrypt transport (TLS/SRTP) and storage; redact PII in transcripts/logs; scope provider data-retention agreements; audit access to recordings; retention policies with provable deletion.',
    alternatives: [],
    limitations: ['Redaction of streaming transcripts is genuinely hard (the credit card number arrives digit by digit)', 'each provider is a data processor to assess'],
    scaling: 'Audit and retention pipelines scale with recording volume.',
    failureModes: ['Secrets/PII in logs', 'recordings kept forever by default', 'provider-side retention nobody read the terms of'],
    related: ['observability', 'session-state'],
  }),
]

export const KNOWLEDGE_BY_ID: Record<string, KnowledgeCard> = Object.fromEntries(
  KNOWLEDGE_CARDS.map((k) => [k.id, k]),
)

export const KNOWLEDGE_CATEGORIES: { id: KnowledgeCard['category']; label: string }[] = [
  { id: 'audio', label: 'Audio' },
  { id: 'networking', label: 'Networking' },
  { id: 'telephony', label: 'Telephony' },
  { id: 'ai', label: 'AI & speech' },
  { id: 'agents', label: 'Agent systems' },
  { id: 'infrastructure', label: 'Infrastructure' },
  { id: 'reliability', label: 'Reliability' },
  { id: 'observability', label: 'Observability' },
  { id: 'security', label: 'Security' },
]
