/**
 * The component registry: every building block an architecture can contain.
 *
 * One catalog feeds the whole app — the Architecture Canvas palette, the call
 * simulator, the validator, the scaling model, the cost engine and the
 * inspector panels all read the same `ComponentSpec`s. Capacity, latency and
 * price figures are SIMULATION ASSUMPTIONS (order-of-magnitude plausible,
 * editable, and labelled as such in the UI).
 */

import type { ComponentSpec, FailureMode } from '../domain/types'
import { FORMATS } from '../models/audio'

// -- failure mode helpers ----------------------------------------------------

const fm = (partial: Omit<FailureMode, 'id'> & { id?: string }): FailureMode => ({
  id: partial.id ?? `${partial.kind}-${partial.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
  ...partial,
})

const providerOutage = (what: string, mitigations: string[]): FailureMode =>
  fm({
    kind: 'unavailable',
    name: `${what} unavailable`,
    callerImpact: 'The call goes silent or dies mid-sentence; new calls fail to start.',
    signal: 'Connection refused / 5xx spike; success rate drops to zero for this dependency.',
    mitigations,
    defaultProbability: 0.02,
    fatal: true,
  })

const timeoutMode = (what: string, impact: string): FailureMode =>
  fm({
    kind: 'timeout',
    name: `${what} timeout`,
    callerImpact: impact,
    signal: 'p99 latency hits the client timeout; requests complete but too late to be useful.',
    mitigations: ['Explicit timeout tuned to the voice budget', 'Retry with backoff (idempotent ops only)', 'Fallback path or spoken filler'],
    defaultProbability: 0.03,
  })

const rateLimit = (what: string): FailureMode =>
  fm({
    kind: 'rate-limit',
    name: `${what} rate limit`,
    callerImpact: 'New calls or new turns fail while existing ones continue; bursty traffic is punished.',
    signal: '429 responses; provider quota dashboard at 100%.',
    mitigations: ['Concurrency caps below quota', 'Token bucket in front of the provider', 'Second provider for overflow'],
    defaultProbability: 0.02,
  })

// -- the catalog -------------------------------------------------------------

export const COMPONENT_SPECS: ComponentSpec[] = [
  // ==========================================================================
  // ENDPOINTS
  // ==========================================================================
  {
    id: 'user',
    name: 'User (caller)',
    short: 'User',
    category: 'endpoint',
    plane: 'media',
    description: 'The human on the call. Source of speech, destination of synthesised audio, and the only latency judge that matters.',
    problemSolved: 'None — the user is the requirement. Everything else exists to serve this box.',
    inputs: ['Agent audio'],
    outputs: ['Speech', 'DTMF key presses', 'Hangup'],
    protocols: ['PSTN', 'WebRTC'],
    latency: { fixedMs: 0 },
    resources: {},
    scaling: { axis: 'managed-external', capacityPerInstance: 1, notes: 'Users scale themselves; your job is to keep up.' },
    failureModes: [
      fm({
        kind: 'disconnect',
        name: 'User hangs up',
        callerImpact: 'Call ends abruptly; any in-flight tool call or booking must be handled gracefully.',
        signal: 'Carrier BYE / WebSocket close; call duration below expectation.',
        mitigations: ['Idempotent tool operations', 'Persist state on every turn, not at call end', 'Post-call SMS follow-up'],
        defaultProbability: 0.05,
      }),
    ],
    alternatives: [],
    whyChoose: 'Not optional.',
    ifItFails: 'The user hanging up IS a failure mode your design must expect: half-finished bookings, orphaned sessions, dangling tool calls.',
    learn: {
      beginner: 'A person talks and listens. Humans notice silence after about 500 ms and find gaps over a second awkward.',
      engineering: 'Human turn-taking gaps average ~200 ms in natural conversation. Perceived latency is measured from the moment they stop speaking to the moment they hear a reply.',
      architecture: 'Every budget in the system derives from human conversational tolerance: roughly 800 ms feels sharp, 1.5 s feels sluggish, 3 s feels broken.',
      infrastructure: 'Concurrency = how many of these are talking at once. Every sizing number in the simulator is denominated in concurrent users.',
      production: 'Users interrupt, mumble, use speakerphones in traffic, and hang up mid-booking. Design for all four.',
      architect: 'When requirements change, re-derive budgets from the user: a voicemail-drop product tolerates seconds; a conversational assistant does not.',
    },
    onMediaPath: true,
    concepts: ['latency-perception'],
  },
  {
    id: 'browser',
    name: 'Browser client',
    short: 'Browser',
    category: 'endpoint',
    plane: 'both',
    description: 'A web page capturing microphone audio (getUserMedia) and playing agent audio, connected via WebRTC or WebSocket.',
    problemSolved: 'Puts a voice agent anywhere a URL can go, with wideband audio and no carrier fees.',
    inputs: ['Microphone (48 kHz float PCM)', 'Agent audio stream'],
    outputs: ['Opus (WebRTC) or PCM16 (WebSocket) upstream audio', 'UI events'],
    protocols: ['WebRTC', 'WebSocket', 'HTTP'],
    audioIn: FORMATS.browserFloat,
    audioOut: FORMATS.opusWebrtc,
    latency: { fixedMs: 15, jitterMs: 10 },
    resources: {},
    scaling: { axis: 'managed-external', capacityPerInstance: 1 },
    failureModes: [
      fm({
        kind: 'disconnect',
        name: 'Tab closed / network change',
        callerImpact: 'Session drops when the laptop lid closes or Wi-Fi hands off to cellular.',
        signal: 'ICE disconnected / WebSocket close without BYE.',
        mitigations: ['Reconnect with session resume token', 'Server-side grace period before killing session state'],
        defaultProbability: 0.04,
      }),
      fm({
        kind: 'degraded-latency',
        name: 'Bad last-mile network',
        callerImpact: 'Choppy audio, delayed replies; the user blames your agent, not their Wi-Fi.',
        signal: 'RTCP jitter/loss reports climbing; jitter buffer depth growing.',
        mitigations: ['Opus FEC + packet loss concealment', 'Adaptive jitter buffer', 'Show connection quality in the UI'],
        defaultProbability: 0.08,
        degradedLatencyMs: 250,
      }),
    ],
    alternatives: ['Native mobile app (more control, app-store friction)', 'Phone call (reach without install)'],
    whyChoose: '48 kHz clean audio (better STT accuracy than any phone line), zero per-minute cost, instant deployment.',
    ifItFails: 'Only that user\'s session is affected — endpoint failures are isolated by nature.',
    learn: {
      beginner: 'The web page uses your microphone and speakers so you can talk to the agent like a phone call, but through the browser.',
      engineering: 'getUserMedia captures 48 kHz float PCM; WebRTC encodes it as Opus over SRTP, or an AudioWorklet ships PCM16 frames over a WebSocket. Echo cancellation runs in the browser.',
      architecture: 'Choosing browser vs phone decides your whole left edge: WebRTC gateway + TURN vs telephony provider + media gateway.',
      infrastructure: 'Each connected browser holds one persistent connection to your media edge — connection-aware scaling starts here.',
      production: 'Autoplay policies, mic permission denials, Bluetooth headsets, and network handoffs are the top field issues.',
      architect: 'If requirements add "reach users with no app and no web page", you add the telephony edge alongside — the core pipeline should not care which edge fed it.',
    },
    onMediaPath: true,
    concepts: ['webrtc', 'websocket', 'opus'],
  },
  {
    id: 'human-agent',
    name: 'Human agent',
    short: 'Human',
    category: 'human',
    plane: 'both',
    description: 'A person in a contact-centre seat who can accept escalated calls with full context.',
    problemSolved: 'Handles what the AI cannot: judgment calls, regulated advice, angry customers, and the long tail of weird requests.',
    inputs: ['Transferred call audio', 'Conversation transcript', 'CRM context screen-pop'],
    outputs: ['Human speech', 'Case notes', 'Disposition codes'],
    protocols: ['SIP', 'WebRTC'],
    latency: { fixedMs: 0 },
    resources: {},
    scaling: {
      axis: 'single-instance',
      capacityPerInstance: 1,
      notes: 'One human ≈ one call at a time. Scaling humans means hiring, scheduling and queueing theory (Erlang C), not autoscaling.',
    },
    cost: { unit: 'per-minute', usdPerUnit: 0.5, note: 'Loaded agent cost assumption; edit freely.' },
    failureModes: [
      fm({
        kind: 'no-capacity',
        name: 'No agent available',
        callerImpact: 'Caller waits in a hold queue, or the transfer fails outright.',
        signal: 'Queue depth and estimated wait time climbing; abandonment rate rising.',
        mitigations: ['Queue with honest wait estimate', 'Scheduled callback offer', 'Voicemail fallback', 'AI continues with reduced scope'],
        defaultProbability: 0.15,
      }),
    ],
    alternatives: ['Callback scheduling', 'Voicemail + ticket', 'Second-tier AI with wider guardrails'],
    whyChoose: 'Required by regulation in some domains; required by customers in all domains eventually.',
    ifItFails: 'The handoff state machine must have a no-agent branch. "Transfer and hope" is not a design.',
    learn: {
      beginner: 'When the AI gets stuck, a real person takes over the call — ideally without the caller repeating everything.',
      engineering: 'A warm transfer moves the media (SIP REFER or conference bridge) AND the context (transcript, intent, CRM record) to the agent desktop before the AI leaves.',
      architecture: 'Handoff is a state transition with failure branches, not a phone feature. CHECK_AVAILABILITY precedes MEDIA_HANDOFF for a reason.',
      infrastructure: 'Erlang C queueing: 80% agent occupancy roughly doubles wait times vs 70%. Staffing is a capacity model like any other.',
      production: 'Transfers fail: agent rejects, desktop crashed, context screen-pop missing. Each needs a scripted recovery the caller hears.',
      architect: 'Under cost pressure, tune the escalation threshold, not the queue: every avoided transfer saves ~50x the AI cost of the call.',
    },
    onMediaPath: true,
    concepts: ['human-handoff'],
  },

  // ==========================================================================
  // TELEPHONY & TRANSPORT
  // ==========================================================================
  {
    id: 'telephony',
    name: 'Telephony provider',
    short: 'Telephony',
    category: 'telephony',
    plane: 'both',
    description: 'The bridge between the phone network (PSTN) and your software: numbers, SIP signalling, and a media stream of call audio.',
    problemSolved: 'You cannot speak PSTN from a container. Someone must terminate carrier trunks and hand you audio as packets.',
    inputs: ['PSTN calls', 'Outbound dial requests (REST)'],
    outputs: ['Call webhooks (control)', 'mu-law/A-law audio stream (media)', 'DTMF events'],
    protocols: ['PSTN', 'SIP', 'RTP', 'WebSocket', 'HTTP'],
    audioIn: FORMATS.telephonyMulaw,
    audioOut: FORMATS.telephonyMulaw,
    latency: { fixedMs: 25, jitterMs: 10, streamingCapable: true },
    resources: { netKbpsPerCall: 128, fdPerCall: 1 },
    scaling: {
      axis: 'managed-external',
      capacityPerInstance: 5000,
      notes: 'Managed CPaaS scales for you but has per-account concurrency quotas and calls-per-second (CPS) dial limits.',
    },
    cost: { unit: 'per-minute', usdPerUnit: 0.014, note: 'Example assumption; edit freely.' },
    failureModes: [
      providerOutage('Telephony provider', ['Second provider with number portability plan', 'Multi-region trunks', 'Status-page-driven incident comms']),
      rateLimit('Outbound CPS'),
      fm({
        kind: 'degraded-latency',
        name: 'Carrier route degradation',
        callerImpact: 'Audio arrives late or clipped; conversations start talking over each other.',
        signal: 'RTP jitter and packet loss on carrier legs; MOS score drops.',
        mitigations: ['Multiple carrier routes', 'Provider with automatic route failover'],
        defaultProbability: 0.03,
        degradedLatencyMs: 180,
      }),
    ],
    dependencies: [],
    alternatives: ['Direct SIP trunk + your own SBC (cheaper per minute, you operate it)', 'WebRTC-only product (no PSTN reach)'],
    whyChoose: 'Reach: everyone has a phone number. CPaaS gets you live in a day; SIP trunks halve the per-minute cost at scale.',
    ifItFails: 'All phone calls fail — inbound callers hear carrier errors. This is a total outage for a phone-first product; it is why serious deployments dual-home carriers.',
    learn: {
      beginner: 'This is the piece that connects real phone calls to your software, turning a call into audio your code can read.',
      engineering: 'Signalling (SIP or webhooks) sets calls up and tears them down; media arrives separately as 8 kHz mu-law frames every 20 ms over RTP or a WebSocket.',
      architecture: 'Telephony fixes your input audio quality (8 kHz, band-limited) and adds a mandatory media hop. Both must be in your latency and accuracy budgets from day one.',
      infrastructure: 'Quotas are the scaling reality: concurrent channel caps and outbound calls-per-second limits. High-volume outbound is paced by a dialer, not a for-loop.',
      production: 'Watch answer rates by carrier and region, post-dial delay, and one-way-audio complaints (almost always NAT or firewall asymmetry).',
      architect: 'At ~500k+ minutes/month, direct SIP trunking typically pays for its operational cost. Below that, CPaaS simplicity usually wins.',
    },
    config: [
      { key: 'provider', label: 'Provider profile', type: 'select', default: 'tel-cpaas', options: [
        { value: 'tel-cpaas', label: 'TwiFlow CPaaS (managed)' },
        { value: 'tel-sip-trunk', label: 'Direct SIP trunk (self-op)' },
      ], help: 'Which simulated telephony profile this node uses.' },
      { key: 'edgeLatencyMs', label: 'Provider edge RTT', type: 'number', default: 25, min: 5, max: 200, step: 5, unit: 'ms', help: 'Round trip to the provider\'s nearest media edge. Grows sharply if their edge is on another continent.' },
    ],
    onMediaPath: true,
    concepts: ['pstn', 'sip', 'rtp', 'sip-trunking', 'dtmf'],
  },
  {
    id: 'sip',
    name: 'SIP signalling',
    short: 'SIP',
    category: 'telephony',
    plane: 'control',
    description: 'Session Initiation Protocol: the control-plane conversation that sets up, modifies and tears down calls. Carries no audio.',
    problemSolved: 'Two endpoints that have never met must agree on who is calling whom, and which codec and address the audio will use.',
    inputs: ['INVITE / BYE / REFER requests'],
    outputs: ['Provisional + final responses (100/180/200/4xx)', 'Negotiated SDP'],
    protocols: ['SIP', 'UDP', 'TCP'],
    latency: { fixedMs: 60, jitterMs: 30 },
    resources: { cpuPerCall: 0.002, memMbPerCall: 0.5 },
    scaling: { axis: 'stateless-horizontal', capacityPerInstance: 2000, notes: 'SIP proxies are near-stateless; dialog state is small.' },
    failureModes: [
      timeoutMode('SIP transaction', 'Calls take forever to connect or never ring; retransmissions flood the proxy.'),
      fm({
        kind: 'unavailable',
        name: 'Registration failure',
        callerImpact: 'Trunk goes unreachable: inbound calls get carrier busy, outbound gets 403.',
        signal: 'REGISTER failures; OPTIONS pings unanswered.',
        mitigations: ['Redundant SBC pair', 'Carrier failover routes', 'OPTIONS-based health checks'],
        defaultProbability: 0.01,
        fatal: true,
      }),
    ],
    alternatives: ['CPaaS webhooks (SIP hidden behind an HTTP API)'],
    whyChoose: 'You run your own trunks or interconnect with a contact-centre platform; SIP is the industry\'s only common tongue.',
    ifItFails: 'New calls cannot be set up or torn down — but established calls keep talking, because media (RTP) flows on a separate path. That separation is the lesson.',
    learn: {
      beginner: 'SIP is the "hello, can we talk?" handshake of phone systems. It rings phones and hangs them up; the voice itself travels separately.',
      engineering: 'Text protocol resembling HTTP: INVITE carries an SDP offer (codecs, RTP address), 200 OK carries the answer, ACK confirms. REFER transfers; re-INVITE renegotiates media mid-call.',
      architecture: 'SIP vs RTP is the canonical control-plane/media-plane split. Signalling can traverse proxies globally while media takes the shortest path.',
      infrastructure: 'Proxies scale horizontally easily. The stateful edge (SBC) is the bottleneck: it polices, encrypts and sometimes anchors media.',
      production: 'NAT breaks SIP constantly (private IPs inside SDP). SBCs, STUN and symmetric RTP exist mostly to fight this.',
      architect: 'Do not build raw SIP handling unless telephony IS your product — buy it (CPaaS/SBC) and spend your complexity budget on the agent.',
    },
    onMediaPath: false,
    concepts: ['sip', 'sdp'],
  },
  {
    id: 'rtp',
    name: 'RTP media stream',
    short: 'RTP',
    category: 'telephony',
    plane: 'media',
    description: 'Real-time Transport Protocol: numbered, timestamped UDP packets carrying 20 ms slices of audio.',
    problemSolved: 'TCP retransmits lost data, which is exactly wrong for live audio — a 200 ms-old packet is garbage. RTP ships audio fast and lets the receiver handle loss.',
    inputs: ['Encoded audio frames'],
    outputs: ['UDP packet stream + RTCP quality reports'],
    protocols: ['RTP', 'RTCP', 'UDP', 'SRTP'],
    audioIn: FORMATS.telephonyMulaw,
    audioOut: FORMATS.telephonyMulaw,
    latency: { fixedMs: 20, jitterMs: 15, streamingCapable: true },
    resources: { netKbpsPerCall: 87, fdPerCall: 2 },
    scaling: { axis: 'stateless-horizontal', capacityPerInstance: 3000 },
    failureModes: [
      fm({
        kind: 'packet-loss',
        name: 'Packet loss',
        callerImpact: 'Syllables vanish; above ~5% loss speech becomes hard to follow and STT accuracy drops.',
        signal: 'RTCP receiver reports show loss fraction; sequence-number gaps.',
        mitigations: ['Jitter buffer + concealment', 'Opus in-band FEC (WebRTC)', 'Better routes / regional media edges'],
        defaultProbability: 0.05,
      }),
      fm({
        kind: 'degraded-latency',
        name: 'Jitter',
        callerImpact: 'The jitter buffer grows to smooth arrival variance, adding tens of ms of delay.',
        signal: 'Interarrival jitter in RTCP; buffer occupancy rising.',
        mitigations: ['Adaptive jitter buffer with a cap', 'QoS/DSCP marking on managed networks'],
        defaultProbability: 0.06,
        degradedLatencyMs: 60,
      }),
    ],
    alternatives: ['WebSocket audio (TCP — simpler, but head-of-line blocking on loss)'],
    whyChoose: 'It is how telephony and WebRTC actually move audio. You choose it implicitly when you choose either.',
    ifItFails: 'Silence in one or both directions while signalling still looks healthy — the classic "call connected, nobody hears anything" ticket.',
    learn: {
      beginner: 'The voice itself travels as a stream of tiny packets, 50 per second, each carrying 1/50th of a second of sound.',
      engineering: 'Each packet: sequence number, timestamp, SSRC, payload type, then 160 bytes of mu-law (at 8 kHz/20 ms). RTCP runs alongside reporting loss, jitter and round-trip time.',
      architecture: 'UDP means the receiver, not the network, owns loss recovery: jitter buffer, concealment, FEC. Any component on this path must be non-blocking.',
      infrastructure: 'Bandwidth math: mu-law RTP ≈ 87 kbit/s per direction with headers. 10,000 calls ≈ 1.7 Gbit/s through your media tier.',
      production: 'One-way audio = NAT/firewall asymmetry. Choppy audio = jitter/loss. RTCP is your black-box flight recorder for both.',
      architect: 'Place media relays near users and providers; every 1,000 km adds ~10 ms round trip that no code can remove.',
    },
    onMediaPath: true,
    concepts: ['rtp', 'rtcp', 'jitter-buffer'],
  },
  {
    id: 'websocket',
    name: 'WebSocket transport',
    short: 'WebSocket',
    category: 'transport',
    plane: 'both',
    description: 'A persistent, bidirectional TCP channel. The workhorse for streaming audio and events between your services and providers.',
    problemSolved: 'HTTP request/response cannot carry a continuous two-way audio conversation; WebSocket keeps one connection open for the whole call.',
    inputs: ['Binary audio frames', 'JSON control events'],
    outputs: ['Binary audio frames', 'JSON control events'],
    protocols: ['WebSocket', 'TCP'],
    latency: { fixedMs: 5, jitterMs: 5, streamingCapable: true },
    resources: { fdPerCall: 1, memMbPerCall: 0.3, netKbpsPerCall: 140 },
    scaling: {
      axis: 'connection-aware',
      capacityPerInstance: 3000,
      stickySessions: true,
      notes: 'Long-lived connections pin calls to servers. Load balancing happens at connect time; draining a server means waiting for calls to end or dropping them.',
    },
    failureModes: [
      fm({
        kind: 'disconnect',
        name: 'Connection drop',
        callerImpact: 'The call\'s audio artery is severed mid-sentence. Without resume logic, the call is dead.',
        signal: 'Abnormal close codes (1006); reconnect storms after an LB deploy.',
        mitigations: ['Client reconnect with jittered backoff', 'Session resume tokens', 'Server-side call-state grace period'],
        defaultProbability: 0.03,
        fatal: false,
      }),
      fm({
        kind: 'queue-saturation',
        name: 'Backpressure',
        callerImpact: 'Audio frames queue faster than the peer drains them; latency compounds every second.',
        signal: 'Socket send buffer growth; bufferedAmount climbing; frames aged > 200 ms on dequeue.',
        mitigations: ['Bounded send queues that drop oldest audio', 'Never do blocking work on the socket loop', 'Monitor queue depth per connection'],
        defaultProbability: 0.04,
      }),
    ],
    alternatives: ['WebRTC data/media (UDP, better on lossy nets, heavier stack)', 'gRPC bidirectional streams (server-to-server)'],
    whyChoose: 'Ubiquitous, firewall-friendly, trivially debuggable. Nearly every streaming STT/TTS/telephony API speaks it.',
    ifItFails: 'Every live call through the failed path drops simultaneously — the blast-radius problem that makes connection-aware scaling and draining a first-class design concern.',
    learn: {
      beginner: 'Instead of asking a question and getting one answer (like loading a web page), the connection stays open so both sides can keep sending — like a phone line for data.',
      engineering: 'HTTP Upgrade handshake, then framed messages both ways. Binary frames carry 20 ms audio chunks (~640 B at 16 kHz PCM16); text frames carry JSON events. Ping/pong detects dead peers.',
      architecture: 'The persistent connection is why voice backends are not stateless web apps: a "request" lasts 5–20 minutes and lives on one specific server.',
      infrastructure: 'Sizing is connections × (memory + fd + bandwidth), not requests/sec. 10k connections on one box is feasible; the risk is the blast radius when it dies.',
      production: 'TCP head-of-line blocking: one lost packet stalls all frames behind it — on bad networks WebSocket audio degrades worse than RTP. Idle LB timeouts silently kill quiet connections.',
      architect: 'Server-to-provider hops: WebSocket everywhere. User-to-server on the open internet: prefer WebRTC when audio quality on bad networks matters.',
    },
    config: [
      { key: 'frameMs', label: 'Audio frame size', type: 'number', default: 20, min: 10, max: 200, step: 10, unit: 'ms', help: 'Bigger frames = fewer packets but more buffering latency.' },
    ],
    onMediaPath: true,
    concepts: ['websocket', 'backpressure'],
  },
  {
    id: 'webrtc',
    name: 'WebRTC transport',
    short: 'WebRTC',
    category: 'transport',
    plane: 'both',
    description: 'The browser\'s real-time media stack: Opus over SRTP with ICE/STUN/TURN NAT traversal, echo cancellation and adaptive jitter buffering built in.',
    problemSolved: 'Getting low-latency, loss-tolerant, echo-cancelled audio out of a browser on an unknown network, without plugins.',
    inputs: ['Microphone track'],
    outputs: ['Opus/SRTP media', 'RTCP quality feedback', 'Data channel messages'],
    protocols: ['WebRTC', 'SRTP', 'RTCP', 'UDP'],
    audioIn: FORMATS.opusWebrtc,
    audioOut: FORMATS.opusWebrtc,
    latency: { fixedMs: 30, jitterMs: 15, streamingCapable: true },
    resources: { cpuPerCall: 0.02, memMbPerCall: 2, netKbpsPerCall: 80, fdPerCall: 3 },
    scaling: {
      axis: 'connection-aware',
      capacityPerInstance: 800,
      stickySessions: true,
      notes: 'Media servers (SFU/gateway) do real DSP per stream; capacity is CPU-bound, far lower than a plain WebSocket relay.',
    },
    failureModes: [
      fm({
        kind: 'unavailable',
        name: 'ICE failure (NAT traversal)',
        callerImpact: 'Connection never establishes — signalling worked, media cannot flow.',
        signal: 'ICE state "failed"; candidates gathered but no pair connects.',
        mitigations: ['TURN servers in every region', 'TCP/TLS TURN fallback for hostile firewalls'],
        defaultProbability: 0.05,
        fatal: true,
      }),
      fm({
        kind: 'packet-loss',
        name: 'Lossy network',
        callerImpact: 'Opus FEC conceals a lot; past ~10% loss, audio audibly degrades.',
        signal: 'RTCP loss fraction; concealment events in getStats().',
        mitigations: ['Opus in-band FEC', 'Bitrate adaptation', 'Regional media edges'],
        defaultProbability: 0.06,
      }),
    ],
    alternatives: ['WebSocket + AudioWorklet PCM (simpler, TCP-bound)', 'Native mobile SDKs'],
    whyChoose: 'The only way to get carrier-grade audio behaviour from a browser: UDP transport, FEC, AEC, adaptive jitter buffer — all free.',
    ifItFails: 'Users behind strict firewalls simply cannot connect. Without TURN you lose 10–20% of enterprise users invisibly.',
    learn: {
      beginner: 'WebRTC is how browsers make real calls: it finds a path to the server through home routers and firewalls, and keeps audio smooth even when the network hiccups.',
      engineering: 'SDP offer/answer negotiates codecs; ICE gathers host/STUN/TURN candidates and probes pairs; media flows as Opus/SRTP; RTCP feeds bitrate adaptation.',
      architecture: 'Browser → WebRTC → media gateway replaces Phone → carrier → telephony provider. Same downstream pipeline, different edge: this symmetry is the architecture insight.',
      infrastructure: 'You now operate media servers and TURN. TURN relays cost bandwidth ×2 (in + out) for the users who need it.',
      production: 'getStats() is the flight recorder: RTT, jitter, loss, concealment. Alert on ICE failure rate by network/ASN, not just averages.',
      architect: 'If your users are on laptops with headsets, WebRTC gives you 48 kHz audio and better STT accuracy than any phone call — a quality edge phones cannot match.',
    },
    onMediaPath: true,
    concepts: ['webrtc', 'ice', 'stun-turn', 'sdp', 'opus'],
  },
  {
    id: 'load-balancer',
    name: 'Load balancer',
    short: 'LB',
    category: 'infrastructure',
    plane: 'both',
    description: 'Distributes incoming connections across server replicas and health-checks them out of rotation when they fail.',
    problemSolved: 'More traffic than one server, and the need to survive any single server dying.',
    inputs: ['Client connections'],
    outputs: ['Balanced connections to healthy backends'],
    protocols: ['TCP', 'HTTP', 'WebSocket'],
    latency: { fixedMs: 2, jitterMs: 1 },
    resources: { netKbpsPerCall: 140, fdPerCall: 2 },
    scaling: { axis: 'managed-external', capacityPerInstance: 50000, notes: 'Managed LBs scale themselves; connection table size and idle timeouts are your knobs.' },
    cost: { unit: 'per-instance-hour', usdPerUnit: 0.03, note: 'Managed LB assumption; edit freely.' },
    failureModes: [
      fm({
        kind: 'disconnect',
        name: 'Idle timeout kills long calls',
        callerImpact: 'Perfectly healthy calls die at exactly N seconds — the tell-tale signature of an LB idle timeout.',
        signal: 'Disconnect histogram spikes at a suspiciously round number (60 s, 350 s).',
        mitigations: ['Raise idle timeout above max call length', 'WebSocket ping/pong keepalives'],
        defaultProbability: 0.02,
      }),
      fm({
        kind: 'overload',
        name: 'Uneven distribution',
        callerImpact: 'Long-lived connections make "least connections at connect time" drift: one server ends up with the long calls.',
        signal: 'Per-backend connection counts diverging over hours.',
        mitigations: ['Connection-count-aware balancing', 'Periodic voluntary drain + reconnect', 'Smaller servers, more of them'],
        defaultProbability: 0.03,
      }),
    ],
    alternatives: ['DNS round-robin (crude, slow failover)', 'Client-side discovery (smart clients pick a server)'],
    whyChoose: 'Mandatory at more than one server. The interesting question is only L4 vs L7 and how it treats long-lived connections.',
    ifItFails: 'Everything behind it is unreachable. Managed LBs are themselves replicated; your job is not to undo that with a single-instance dependency behind them.',
    learn: {
      beginner: 'A traffic director standing in front of your servers, sending each new call to a healthy one.',
      engineering: 'L4 balances TCP connections (cheap, opaque); L7 understands HTTP/WebSocket (routing, headers, but must proxy every frame). Health checks eject bad backends.',
      architecture: 'With long-lived voice connections the LB only decides placement at connect time. Rebalancing mid-call means dropping calls — so placement policy matters far more than for web traffic.',
      infrastructure: 'Watch connection table limits and per-backend skew. Voice LBs are sized by concurrent connections and bandwidth, not requests/sec.',
      production: 'The two classic incidents: idle timeout killing quiet calls, and deploys that "drain" by cutting connections instead of waiting.',
      architect: 'For very large fleets, move placement into a connection broker: clients ask "which server?", then connect directly — the LB stops carrying media.',
    },
    onMediaPath: true,
    concepts: ['load-balancing', 'connection-draining'],
  },

  // ==========================================================================
  // MEDIA & SPEECH
  // ==========================================================================
  {
    id: 'media-gateway',
    name: 'Media gateway / voice server',
    short: 'Media GW',
    category: 'media',
    plane: 'media',
    description: 'The per-call media hub: terminates the transport (Twilio WS / RTP / WebRTC), converts formats, runs VAD, fans audio to STT and streams TTS back. In this repo, this is the Pipecat process.',
    problemSolved: 'Someone has to own the real-time loop: byte-level formats, 20 ms deadlines, barge-in, and the plumbing between transport and AI services.',
    inputs: ['Caller audio (mu-law/Opus/PCM)', 'TTS audio', 'Control commands'],
    outputs: ['PCM16 to STT', 'Encoded audio to caller', 'Call events'],
    protocols: ['WebSocket', 'RTP', 'internal'],
    audioIn: FORMATS.telephonyMulaw,
    audioOut: FORMATS.pcm16k,
    latency: { fixedMs: 10, jitterMs: 5, streamingCapable: true, queueingAtLoadMs: 150 },
    resources: { cpuPerCall: 0.06, memMbPerCall: 45, netKbpsPerCall: 300, fdPerCall: 4, baseCpu: 0.3, baseMemMb: 350 },
    scaling: {
      axis: 'connection-aware',
      capacityPerInstance: 50,
      warmupSeconds: 45,
      stickySessions: true,
      notes: 'ASSUMPTION: ~50 concurrent calls per 4-vCPU instance for a Python/Pipecat-style server; a tuned native server carries far more. The pattern (CPU-bound, sticky) is what matters.',
    },
    cost: { unit: 'per-instance-hour', usdPerUnit: 0.17, note: '4 vCPU node assumption; edit freely.' },
    failureModes: [
      fm({
        kind: 'overload',
        name: 'CPU saturation',
        callerImpact: 'Audio processing misses its 20 ms deadlines: choppy audio, late VAD, delayed everything — on every call on the box.',
        signal: 'CPU > 85%, event-loop lag, frame-processing time > frame duration.',
        mitigations: ['Admission control (refuse call #51)', 'Autoscale on connections, not just CPU', 'Move non-media work off this tier'],
        defaultProbability: 0.04,
      }),
      fm({
        kind: 'unavailable',
        name: 'Instance dies mid-call',
        callerImpact: 'Every call on the instance drops at once. Callers must be able to redial into a fresh server with context restored.',
        signal: 'Health check failures; a step drop in active connections.',
        mitigations: ['Small instances (limit blast radius)', 'Session state in Redis, not process memory', 'Carrier-level redial/redirect'],
        defaultProbability: 0.01,
        fatal: true,
      }),
      fm({
        kind: 'memory-pressure',
        name: 'Buffer bloat / leak',
        callerImpact: 'Slow death: per-call buffers grow, GC pauses lengthen, audio stutters, then OOM.',
        signal: 'RSS climbing without connection growth; GC pause p99 rising.',
        mitigations: ['Bounded per-call buffers', 'Memory limits + restart policy', 'Leak tests with long soak calls'],
        defaultProbability: 0.02,
      }),
    ],
    dependencies: ['websocket'],
    alternatives: ['Pipecat/LiveKit Agents-style framework (this repo)', 'FreeSWITCH/Asterisk + ESL', 'Fully managed voice platform'],
    whyChoose: 'This is the heart you cannot outsource without outsourcing the product: whoever owns the media loop owns latency, barge-in and cost.',
    ifItFails: 'Its blast radius IS its concurrent calls. The single most important sizing decision in the whole architecture is how many calls you let one of these hold.',
    learn: {
      beginner: 'The switchboard of one call: it receives the caller\'s audio, sends it to the transcriber, and plays the agent\'s voice back.',
      engineering: 'An event loop juggling per-call tasks: decode mu-law → PCM, feed VAD, fan out to STT over WebSocket, receive TTS chunks, encode and pace them back at exactly real time.',
      architecture: 'Everything latency-critical converges here, so it must do nothing slow: no DB calls, no synchronous HTTP, no disk writes on the media path.',
      infrastructure: 'The canonical connection-aware tier: sticky sessions, warmup time, drain-before-deploy. Capacity per instance decides your blast radius.',
      production: 'The failure that teaches the most: one overloaded gateway degrades every call it holds. Admission control beats graceful degradation here.',
      architect: 'Under scale pressure, split it: dumb packet relay (huge capacity) + per-call agent workers (small blast radius), connected by a queue-free internal stream.',
    },
    config: [
      { key: 'callsPerInstance', label: 'Calls per instance', type: 'number', default: 50, min: 5, max: 500, step: 5, unit: 'calls', help: 'Capacity assumption per media server instance. Lower = smaller blast radius, more instances.' },
    ],
    onMediaPath: true,
    concepts: ['media-plane', 'backpressure', 'connection-draining'],
  },
  {
    id: 'vad',
    name: 'Voice activity detection',
    short: 'VAD',
    category: 'media',
    plane: 'media',
    description: 'A tiny model watching the audio stream and deciding, frame by frame: is this speech or silence?',
    problemSolved: 'The system needs to know when the user starts talking (barge-in!) and stops talking (their turn is over) — without waiting for the STT.',
    inputs: ['PCM frames (16 kHz)'],
    outputs: ['SPEECH_STARTED / SPEECH_ENDED events'],
    protocols: ['internal'],
    audioIn: FORMATS.pcm16k,
    latency: { fixedMs: 30, streamingCapable: true },
    resources: { cpuPerCall: 0.01, memMbPerCall: 5 },
    scaling: { axis: 'stateless-horizontal', capacityPerInstance: 500, notes: 'Runs in-process on the media gateway; scales with it.' },
    failureModes: [
      fm({
        kind: 'partial-output',
        name: 'Threshold too sensitive',
        callerImpact: 'Keyboard clicks and breaths become "speech": the agent stops talking for phantom interruptions.',
        signal: 'High rate of SPEECH_STARTED < 100 ms long; barge-ins with no subsequent transcript.',
        mitigations: ['Minimum speech duration gate', 'Energy + model confidence combined', 'Tune on real call audio'],
        defaultProbability: 0.05,
      }),
      fm({
        kind: 'partial-output',
        name: 'Silence timeout too short',
        callerImpact: 'The agent answers into the user\'s thinking pause, cutting off "...and also I wanted to ask—".',
        signal: 'User speech resumes < 300 ms after agent starts; rising interruption rate.',
        mitigations: ['Longer endpoint timeout', 'Semantic turn detection on top of VAD', 'Prosody cues (falling pitch)'],
        defaultProbability: 0.05,
      }),
    ],
    alternatives: ['Energy-threshold gate (cheap, fooled by noise)', 'Semantic endpointing in the STT', 'Native S2S turn detection'],
    whyChoose: 'Sub-50 ms speech/no-speech decisions are the foundation for interruption handling and endpointing. Everything conversational sits on this.',
    ifItFails: 'The agent either talks over the user constantly or waits forever. A voice agent with broken VAD is unusable regardless of how good the LLM is.',
    learn: {
      beginner: 'A listener that raises its hand the instant you start speaking and lowers it when you stop.',
      engineering: 'A small NN (Silero-class) scoring 30 ms windows with speech probability; hysteresis + minimum-duration filters turn scores into clean start/stop events.',
      architecture: 'VAD answers "is sound happening?"; turn detection answers "is the thought finished?". Confusing the two produces agents that interrupt. Both belong on the gateway, in-process — a network hop here would eat the whole point.',
      infrastructure: 'Cheap (~1% CPU per call) but latency-critical; it is why the media tier is CPU-sized rather than IO-sized.',
      production: 'Tune on real production audio: cars, speakerphones, hold music. Lab-tuned thresholds fail in the field.',
      architect: 'The silence timeout IS your conversational feel: 300 ms feels eager, 800 ms feels polite, 1500 ms feels broken. It is a product decision expressed in milliseconds.',
    },
    config: [
      { key: 'speechThreshold', label: 'Speech threshold', type: 'number', default: 0.5, min: 0.1, max: 0.9, step: 0.05, help: 'Model confidence needed to declare speech. Lower = more sensitive.' },
      { key: 'minSpeechMs', label: 'Min speech duration', type: 'number', default: 120, min: 20, max: 500, step: 20, unit: 'ms', help: 'Sounds shorter than this are ignored (coughs, clicks).' },
      { key: 'silenceTimeoutMs', label: 'Silence timeout', type: 'number', default: 600, min: 100, max: 2000, step: 50, unit: 'ms', help: 'Silence needed to declare the turn over. The single biggest perceived-latency knob.' },
    ],
    onMediaPath: true,
    concepts: ['vad', 'turn-detection', 'barge-in'],
  },
  {
    id: 'stt',
    name: 'Speech-to-text',
    short: 'STT',
    category: 'speech',
    plane: 'media',
    description: 'Turns the audio stream into text — ideally as a stream of partial hypotheses while the user is still talking.',
    problemSolved: 'LLMs read text. Someone must turn 16,000 samples per second into words, fast and accurately enough to act on.',
    inputs: ['PCM16 16 kHz audio'],
    outputs: ['Partial transcripts', 'Final transcripts + confidence'],
    protocols: ['WebSocket', 'gRPC', 'HTTP'],
    audioIn: FORMATS.pcm16k,
    latency: { fixedMs: 200, firstByteMs: 200, jitterMs: 60, streamingCapable: true },
    throughputPerInstance: 400,
    resources: { netKbpsPerCall: 256, fdPerCall: 1 },
    scaling: { axis: 'managed-external', capacityPerInstance: 400, notes: 'Managed: concurrency quota per account. Self-hosted: GPU streams per node.' },
    cost: { unit: 'per-minute', usdPerUnit: 0.0059, note: 'Example assumption; edit freely.' },
    failureModes: [
      providerOutage('STT', ['Fallback STT provider (different vendor)', 'Regional endpoints', 'Graceful "I did not catch that" + DTMF fallback']),
      timeoutMode('STT finalization', 'The user stopped talking but no final transcript arrives; the agent stands mute exactly when it should answer.'),
      rateLimit('STT concurrency'),
      fm({
        kind: 'partial-output',
        name: 'Accuracy degradation',
        callerImpact: 'Misheard numbers and names send the agent confidently down the wrong path.',
        signal: 'Confidence scores dropping; tool-call validation failures; users repeating themselves.',
        mitigations: ['Confirm critical entities aloud', 'Phrase hints / custom vocabulary', 'Wideband audio where possible'],
        defaultProbability: 0.08,
      }),
    ],
    alternatives: ['Managed streaming (fast partials, per-minute fees)', 'Self-hosted Whisper-class (accuracy + residency, you run GPUs)', 'S2S model (no separate STT at all)'],
    whyChoose: 'Streaming vs batch here is THE latency decision: partials let the endpointing and the LLM start before the user finishes.',
    ifItFails: 'The agent goes deaf. Without a fallback the call is over; with one, you ride out the outage at slightly worse accuracy.',
    learn: {
      beginner: 'The transcriber: it writes down what the caller says, updating its guess live as they speak.',
      engineering: 'Audio frames stream up a WebSocket; interim hypotheses stream down and may revise earlier words; end-of-speech triggers a final, stable transcript with confidence.',
      architecture: 'Partials are what make sub-second agents possible: endpointing, intent detection and even LLM prefill can start on interim text.',
      infrastructure: 'One held connection per live call — provider concurrency quotas are your real capacity ceiling, discovered at the worst time if not planned.',
      production: 'Watch WER proxies (confidence, retry phrases), finalization latency p99, and per-language accuracy separately.',
      architect: '8 kHz telephony audio costs meaningful accuracy vs 48 kHz browser audio. If accuracy is the requirement, the transport choice upstream is an STT decision.',
    },
    config: [
      { key: 'provider', label: 'Provider profile', type: 'select', default: 'stt-stream-fast', options: [
        { value: 'stt-stream-fast', label: 'FastStream (managed, streaming)' },
        { value: 'stt-stream-bigcloud', label: 'CloudScale (managed, streaming)' },
        { value: 'stt-whisper-batch', label: 'OpenWhisper (self-hosted, batch)' },
        { value: 'stt-whisper-stream', label: 'OpenWhisper streaming (self-hosted)' },
        { value: 'stt-indic', label: 'IndicVoice (India multilingual)' },
      ], help: 'Simulated STT profile.' },
    ],
    onMediaPath: true,
    concepts: ['stt', 'streaming'],
  },
  {
    id: 'tts',
    name: 'Text-to-speech',
    short: 'TTS',
    category: 'speech',
    plane: 'media',
    description: 'Turns the agent\'s text into audio — ideally streaming the first chunk while the rest is still being generated.',
    problemSolved: 'The reply exists as text; the caller needs a voice. Time-to-first-audio here is the last leg of perceived latency.',
    inputs: ['Text (possibly incremental sentences from the LLM)'],
    outputs: ['Audio chunks (PCM/Opus/MP3)'],
    protocols: ['WebSocket', 'HTTP'],
    audioOut: FORMATS.pcm24k,
    latency: { fixedMs: 180, firstByteMs: 180, jitterMs: 50, streamingCapable: true },
    throughputPerInstance: 200,
    resources: { netKbpsPerCall: 384, fdPerCall: 1 },
    scaling: { axis: 'managed-external', capacityPerInstance: 200 },
    cost: { unit: 'per-1k-chars', usdPerUnit: 0.18, note: 'Example assumption; edit freely.' },
    failureModes: [
      providerOutage('TTS', ['Fallback TTS (cheaper voice beats silence)', 'Cache common phrases as audio', 'Text-channel fallback where one exists']),
      timeoutMode('TTS first audio', 'The reply is ready but the voice is not: dead air after the user clearly should have heard something.'),
      rateLimit('TTS concurrency'),
    ],
    alternatives: ['Premium streaming (brand voice, cost)', 'Hyperscaler neural (10x cheaper)', 'Self-hosted CPU TTS (utility quality, ~free)'],
    whyChoose: 'Voice quality is brand; time-to-first-audio is UX; price per character is unit economics. Pick two per tier, or route by call type.',
    ifItFails: 'The agent understands everything and cannot speak — the most maddening outage. Fallback-to-any-voice is the canonical reliability pattern here.',
    learn: {
      beginner: 'The agent\'s voice. Good ones start speaking a fraction of a second after being given text.',
      engineering: 'Sentence fragments stream in; audio chunks stream out at N× real time. The client paces playback at exactly 1× and keeps a small buffer against generation jitter.',
      architecture: 'Streaming TTS + sentence-chunked LLM output is why modern agents feel instant: speak sentence 1 while sentence 2 generates.',
      infrastructure: 'Egress-heavy: 24 kHz PCM back to the gateway is ~384 kbit/s per call before re-encoding for the carrier.',
      production: 'Time-to-first-audio p99 and mid-utterance underruns (generation slower than playback) are the two SLIs that matter.',
      architect: 'Barge-in support must reach here: cancelling synthesis mid-utterance saves both latency and characters billed.',
    },
    config: [
      { key: 'provider', label: 'Provider profile', type: 'select', default: 'tts-premium-stream', options: [
        { value: 'tts-premium-stream', label: 'VelvetVoice (premium streaming)' },
        { value: 'tts-cloud-standard', label: 'CloudNeural (standard streaming)' },
        { value: 'tts-selfhosted', label: 'PiperLocal (self-hosted CPU)' },
        { value: 'tts-batch-mp3', label: 'BatchVoice (non-streaming MP3)' },
      ], help: 'Simulated TTS profile.' },
    ],
    onMediaPath: true,
    concepts: ['tts', 'streaming'],
  },

  // ==========================================================================
  // INTELLIGENCE & RUNTIME
  // ==========================================================================
  {
    id: 'llm',
    name: 'Large language model',
    short: 'LLM',
    category: 'intelligence',
    plane: 'media',
    description: 'The reasoning engine: reads the conversation, decides what to say or which tool to call, streams tokens back.',
    problemSolved: 'Understanding intent, holding a coherent conversation, and choosing actions — the part scripted IVRs never solved.',
    inputs: ['System prompt + conversation history + tool results'],
    outputs: ['Token stream', 'Tool call requests'],
    protocols: ['HTTP/2'],
    latency: { fixedMs: 220, firstByteMs: 220, perUnitMs: 8.3, unit: 'token', jitterMs: 80, streamingCapable: true },
    throughputPerInstance: 500,
    resources: {},
    scaling: { axis: 'managed-external', capacityPerInstance: 500, notes: 'Managed: tokens/min + requests/min quotas. Self-hosted: GPU batch scheduling.' },
    cost: { unit: 'per-1k-input-tokens', usdPerUnit: 0.00015, note: 'Example assumption; edit freely.' },
    failureModes: [
      timeoutMode('LLM', 'The agent takes a breath and never exhales: the single most common cause of awkward dead air.'),
      providerOutage('LLM', ['Second model/vendor with prompt parity tests', 'Scripted fallback for critical flows', 'Queue + retry for non-realtime work']),
      rateLimit('LLM tokens-per-minute'),
      fm({
        kind: 'partial-output',
        name: 'Malformed tool call',
        callerImpact: 'The model calls a tool with a bad argument; without validation, garbage hits your backend.',
        signal: 'Schema validation failures on tool arguments.',
        mitigations: ['Validate every tool call against a schema', 'Re-prompt once with the error', 'Fall back to asking the user'],
        defaultProbability: 0.04,
      }),
    ],
    alternatives: ['Fast small model (voice default)', 'Flagship model (hard reasoning, slower)', 'Self-hosted open weights (control + residency)'],
    whyChoose: 'Time-to-first-token and tokens/sec are conversational latency; capability is task success. Route per turn if one model cannot give you both.',
    ifItFails: 'The agent hears perfectly and has nothing to say. Every serious deployment defines what the voice does during LLM trouble: filler, retry, or human.',
    learn: {
      beginner: 'The brain: it reads what you said and everything so far, then decides what to say back or what to look up.',
      engineering: 'Prefill (reading input) sets time-to-first-token; decode streams at N tokens/sec. Tool calls arrive as structured JSON deltas mid-stream.',
      architecture: 'Streaming is non-negotiable for voice: you need sentence 1 in ~300 ms, not the full reply in 3 s. Prompt size is a latency tax on every single turn.',
      infrastructure: 'Quotas are denominated in tokens/min — a concurrency of 500 calls with chatty prompts can hit TPM limits before request limits.',
      production: 'Tail latency is the product: p50 of 400 ms with p99 of 4 s means 1 in 100 turns feels broken. Timeout + spoken filler beats waiting.',
      architect: 'Two-model routing (small for routine turns, large for hard ones) is the standard cost/latency/capability compromise once traffic is real.',
    },
    config: [
      { key: 'provider', label: 'Model profile', type: 'select', default: 'llm-fast-small', options: [
        { value: 'llm-fast-small', label: 'Swift-Mini (fast, small)' },
        { value: 'llm-flagship', label: 'Atlas-Large (flagship)' },
        { value: 'llm-selfhosted', label: 'Llama-Home (self-hosted)' },
      ], help: 'Simulated LLM profile.' },
      { key: 'contextTokens', label: 'Context per turn', type: 'number', default: 1800, min: 300, max: 20000, step: 100, unit: 'tokens', help: 'System prompt + history + tools sent every turn. Latency and cost both scale with it.' },
    ],
    onMediaPath: true,
    concepts: ['llm', 'function-calling', 'streaming'],
  },
  {
    id: 's2s',
    name: 'Speech-to-speech model',
    short: 'S2S',
    category: 'intelligence',
    plane: 'media',
    description: 'A single realtime model that consumes audio and produces audio: STT, LLM and TTS collapsed into one provider session.',
    problemSolved: 'Removes two pipeline hops and their orchestration; gives native prosody, laughter, hesitation and built-in turn taking.',
    inputs: ['Caller audio stream'],
    outputs: ['Agent audio stream', 'Tool calls', 'Transcripts (if exposed)'],
    protocols: ['WebRTC', 'WebSocket'],
    audioIn: FORMATS.pcm24k,
    audioOut: FORMATS.pcm24k,
    latency: { fixedMs: 450, firstByteMs: 450, jitterMs: 120, streamingCapable: true },
    resources: { netKbpsPerCall: 768, fdPerCall: 1 },
    scaling: { axis: 'managed-external', capacityPerInstance: 100, notes: 'Session-based quotas; per-minute pricing runs while connected.' },
    cost: { unit: 'per-minute', usdPerUnit: 0.18, note: 'Example assumption; edit freely.' },
    failureModes: [
      providerOutage('S2S model', ['Fallback to a full STT→LLM→TTS pipeline (keep one warm!)', 'Graceful "call me back" script']),
      fm({
        kind: 'partial-output',
        name: 'Opaque misunderstanding',
        callerImpact: 'With no intermediate transcript to inspect or correct, a mishearing is invisible until the wrong answer comes out.',
        signal: 'Task failure without any pipeline error; QA listening is the only reliable detector.',
        mitigations: ['Use providers that expose transcripts', 'Confirm critical entities verbally', 'Shadow STT for audit'],
        defaultProbability: 0.05,
      }),
    ],
    alternatives: ['Composed streaming pipeline (control, mix-and-match, cheaper at scale)'],
    whyChoose: 'Fastest path to a natural-sounding agent, superb interruption handling — at the price of control, auditability and vendor lock-in.',
    ifItFails: 'You lose STT, LLM and TTS simultaneously — the concentration-of-risk tradeoff made physical. The mitigation is an entire warm fallback pipeline.',
    learn: {
      beginner: 'One AI that listens and talks directly, like a person — no separate transcriber or voice generator.',
      engineering: 'A persistent realtime session (WebRTC/WebSocket); audio deltas up, audio deltas down, tool calls as events. Turn detection is server-side.',
      architecture: 'The A-vs-C architecture question: composed pipeline (control, per-piece choice, per-piece fallback) vs S2S (naturalness, simplicity, one throat to choke).',
      infrastructure: 'Per-minute session pricing changes the cost curve: silence costs the same as speech. Long quiet calls are expensive.',
      production: 'Debugging is harder: no transcript boundary to log at. Contract for transcript access or run a shadow STT.',
      architect: 'Hybrid is common: S2S for the conversational shell, with a text-pipeline escape hatch for turns needing audit or complex tools.',
    },
    onMediaPath: true,
    concepts: ['s2s', 'turn-detection'],
  },
  {
    id: 'agent-runtime',
    name: 'Agent runtime',
    short: 'Runtime',
    category: 'runtime',
    plane: 'both',
    description: 'The orchestrator of one conversation: state machine, context builder, tool dispatcher, interruption logic. In this repo: the Pipecat pipeline + tool registry.',
    problemSolved: 'STT, LLM and TTS are services; a conversation is a process. Something must own turn lifecycle, memory, tool execution and error recovery.',
    inputs: ['Final transcripts', 'LLM outputs', 'Tool results', 'Call events'],
    outputs: ['LLM prompts', 'Tool invocations', 'TTS text', 'State updates'],
    protocols: ['internal'],
    latency: { fixedMs: 15, jitterMs: 5 },
    resources: { cpuPerCall: 0.02, memMbPerCall: 20, baseCpu: 0.2, baseMemMb: 200 },
    scaling: { axis: 'connection-aware', capacityPerInstance: 80, stickySessions: true, warmupSeconds: 30 },
    cost: { unit: 'per-instance-hour', usdPerUnit: 0.17, note: 'Runs with/near the media gateway; edit freely.' },
    failureModes: [
      fm({
        kind: 'partial-output',
        name: 'State machine wedge',
        callerImpact: 'The call gets stuck: agent neither speaks nor listens. Usually a missing transition for an unexpected event order.',
        signal: 'Calls with no state transition for > N seconds; watchdog alarms.',
        mitigations: ['Watchdog timer per state', 'Explicit transition table (reject, log, recover)', 'Kill-switch to human'],
        defaultProbability: 0.02,
      }),
      timeoutMode('Tool dispatch', 'A slow tool freezes the turn; without a timeout + filler, the caller hears the void.'),
    ],
    dependencies: ['llm'],
    alternatives: ['Pipeline frameworks (Pipecat, LiveKit Agents)', 'Hand-rolled asyncio loop (this repo\'s ancestor)', 'Managed agent platforms'],
    whyChoose: 'This is where your product logic lives. Frameworks give you the loop; the states, tools and recovery behavior are always yours.',
    ifItFails: 'The conversation loses its mind: context gone, tools orphaned. Keeping its state external (Redis) is what makes crashes survivable.',
    learn: {
      beginner: 'The conductor: it decides when to listen, when to think, when to talk, and when to look something up.',
      engineering: 'An event-driven state machine (LISTENING → PROCESSING → SPEAKING → INTERRUPTED...) with a context builder that assembles each LLM prompt and a dispatcher that validates and executes tool calls.',
      architecture: 'Separating runtime from media gateway is optional at small scale and mandatory at large: media scales by bandwidth, runtime by conversation complexity.',
      infrastructure: 'Sticky per call. If state lives in process memory, a deploy drops every conversation — external session state is what buys you zero-downtime deploys.',
      production: 'The bugs are event-ordering bugs: transcript arriving after barge-in, tool result after hangup. Log every transition with the event that caused it.',
      architect: 'Design the runtime API so the media layer and the intelligence layer are both swappable: transcripts in, text/tool-calls out.',
    },
    onMediaPath: true,
    concepts: ['state-machines', 'function-calling', 'memory'],
  },
  {
    id: 'tool-api',
    name: 'Tool / External API',
    short: 'Tool',
    category: 'external',
    plane: 'control',
    description: 'A business capability the agent can invoke: order lookup, premium calculator, CRM, payments, calendar booking.',
    problemSolved: 'An agent that can only talk is a demo. Tools connect the conversation to systems that do things.',
    inputs: ['Validated, structured arguments'],
    outputs: ['Structured results', 'Domain errors'],
    protocols: ['HTTP', 'gRPC'],
    latency: { fixedMs: 250, jitterMs: 150 },
    throughputPerInstance: 300,
    resources: {},
    scaling: { axis: 'managed-external', capacityPerInstance: 300, notes: 'Often a legacy system with a hard QPS ceiling nobody wrote down.' },
    failureModes: [
      timeoutMode('Tool call', 'The premium calculation hangs; the agent must speak filler, retry, or gracefully give up — silence is not an option.'),
      providerOutage('Backend API', ['Timeout + spoken fallback', 'Cache recent reads', 'Queue writes for async completion', 'Degrade to "I will text you the details"']),
      fm({
        kind: 'rate-limit',
        name: 'Legacy system QPS ceiling',
        callerImpact: 'The CRM built for 50 human agents meets 500 concurrent AI calls; everything behind it slows.',
        signal: 'Rising latency + 429/503 from the backend as call volume grows.',
        mitigations: ['Client-side concurrency cap', 'Read replica / cache tier', 'Bulk prefetch where predictable'],
        defaultProbability: 0.04,
      }),
    ],
    alternatives: ['Direct DB access (fast, tight coupling)', 'Event → async worker (for anything not needed mid-sentence)'],
    whyChoose: 'The value of the product lives here. The design question is only: which calls must block the conversation, and which can be async?',
    ifItFails: 'The agent must keep talking: acknowledge, offer alternatives, promise follow-up. Tool failure handling IS conversational design.',
    learn: {
      beginner: 'The agent\'s hands: while the voice talks to you, tools look up your order or book your slot.',
      engineering: 'LLM emits a function call → runtime validates args against a schema → executes with a timeout → feeds the result back for the model to phrase.',
      architecture: 'Tool latency lands inside a live turn. >500 ms needs spoken filler ("let me check that"); >2 s needs async + callback design.',
      infrastructure: 'AI concurrency multiplies backend load in a way human agents never did. Capacity-test the tools, not just the pipeline.',
      production: 'Idempotency is everything for writes: retried webhooks and retried tool calls must not double-book (this repo\'s booking flow hashes an idempotency key for exactly this reason).',
      architect: 'Sort every tool into blocking (sub-second reads on the turn) vs async (writes, slow queries via queue + spoken promise). The sorting decides half your infra.',
    },
    config: [
      { key: 'latencyMs', label: 'Typical latency', type: 'number', default: 250, min: 20, max: 5000, step: 10, unit: 'ms', help: 'Median backend response time. Watch what >800 ms does to the turn.' },
      { key: 'timeoutMs', label: 'Timeout', type: 'number', default: 1500, min: 100, max: 10000, step: 100, unit: 'ms', help: 'How long the runtime waits before giving up on the tool.' },
    ],
    onMediaPath: false,
    concepts: ['function-calling', 'timeout-budgets', 'idempotency'],
  },

  // ==========================================================================
  // STATE & DATA
  // ==========================================================================
  {
    id: 'redis',
    name: 'Redis',
    short: 'Redis',
    category: 'state',
    plane: 'control',
    description: 'In-memory data store: session state, distributed locks, rate limiting, pub/sub, hot cache — the sub-millisecond memory of the platform.',
    problemSolved: 'Live call state needs microsecond reads and must survive a media-server crash; process memory gives you the speed but not the survival.',
    inputs: ['GET/SET/HSET, locks, pub/sub'],
    outputs: ['Values in < 1 ms (same AZ)'],
    protocols: ['Redis', 'TCP'],
    latency: { fixedMs: 1, jitterMs: 1 },
    throughputPerInstance: 80000,
    resources: { baseMemMb: 2048 },
    scaling: { axis: 'partitioned', capacityPerInstance: 80000, notes: 'Ops/sec per node assumption; cluster mode shards by key. Memory is the other ceiling.' },
    cost: { unit: 'per-instance-hour', usdPerUnit: 0.09, note: 'Cache node assumption; edit freely.' },
    failureModes: [
      fm({
        kind: 'unavailable',
        name: 'Redis down',
        callerImpact: 'Depends entirely on your design: with in-process fallback, calls continue and lose crash-recovery; without it, every turn that touches state fails.',
        signal: 'Connection errors; failover event in the managed console.',
        mitigations: ['Replica + automatic failover', 'Local in-process cache as degraded mode', 'Do not put Redis on the per-frame media path'],
        defaultProbability: 0.01,
        fatal: false,
      }),
      fm({
        kind: 'memory-pressure',
        name: 'Eviction storm',
        callerImpact: 'Session keys for live calls get evicted; agents suddenly forget conversations mid-call.',
        signal: 'evicted_keys > 0; memory at maxmemory.',
        mitigations: ['TTL hygiene on every key', 'noeviction + alerting for session data', 'Size for peak concurrent sessions'],
        defaultProbability: 0.02,
      }),
    ],
    alternatives: ['In-process memory (fast, dies with the process)', 'PostgreSQL (durable, 10-50x slower)', 'Memcached (cache only, no structures)'],
    whyChoose: 'The standard answer to "where does live session state live so that a server crash is not a lobotomy".',
    ifItFails: 'The teaching point: decide *before* the outage whether Redis is availability-critical or performance-critical in your design. Both are valid; not choosing is not.',
    learn: {
      beginner: 'A super-fast shared notepad every server can read and write, so any server can pick up a conversation.',
      engineering: 'Single-threaded event loop serving in-memory structures (hashes for sessions, sorted sets for queues, pub/sub for events) in ~100 µs server-side.',
      architecture: 'Ephemeral-state ownership: call state in Redis with TTLs, durable facts in Postgres. Each store does what it is for.',
      infrastructure: 'Scale reads with replicas, writes/memory with cluster sharding. Watch ops/sec, memory, and hot keys (a single popular key defeats sharding).',
      production: 'Failover takes seconds — what do live calls do during those seconds? That answer belongs in your design doc, not your incident review.',
      architect: 'Keep it off the per-frame path: media loops read state at turn boundaries, not per 20 ms frame. Then Redis latency is irrelevant and its outage is survivable.',
    },
    onMediaPath: false,
    concepts: ['redis', 'session-state'],
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    short: 'Postgres',
    category: 'data',
    plane: 'control',
    description: 'The durable system of record: customers, orders, bookings, call records, transcripts, audit trails.',
    problemSolved: 'Facts that must survive restarts, be queried in ways you have not thought of yet, and hold up transactional invariants (no double bookings).',
    inputs: ['SQL queries + transactions'],
    outputs: ['Rows, constraints enforced'],
    protocols: ['SQL', 'TCP'],
    latency: { fixedMs: 8, jitterMs: 6 },
    throughputPerInstance: 3000,
    resources: { baseCpu: 2, baseMemMb: 8192 },
    scaling: { axis: 'vertical', capacityPerInstance: 3000, notes: 'Queries/sec assumption. Reads scale via replicas; writes scale vertically until you shard — which you should postpone as long as possible.' },
    cost: { unit: 'per-instance-hour', usdPerUnit: 0.35, note: 'Managed instance assumption; edit freely.' },
    failureModes: [
      fm({
        kind: 'no-capacity',
        name: 'Connection pool exhaustion',
        callerImpact: 'The classic voice-scale failure: 1,000 concurrent calls each holding a DB connection kills a database sized for a web app.',
        signal: '"too many connections"; pool wait time climbing.',
        mitigations: ['PgBouncer/pooler in transaction mode', 'Connections per call ≈ 0 (acquire per query)', 'Cap pool size well below max_connections'],
        defaultProbability: 0.04,
      }),
      timeoutMode('Query', 'A slow query inside a live turn is dead air with a database excuse.'),
      providerOutage('Database', ['HA standby + automatic failover', 'Read replicas for lookups', 'Queue writes during failover']),
    ],
    alternatives: ['MySQL (equivalent here)', 'DynamoDB-class KV (scale, weaker queries)', 'Supabase (managed Postgres — what this repo uses)'],
    whyChoose: 'Transactions, constraints and SQL cover 95% of a voice product\'s data needs, and every engineer knows it.',
    ifItFails: 'Live audio should keep flowing — if it does not, the DB was on your media path and that is the finding. Reads degrade to cache; writes queue.',
    learn: {
      beginner: 'The filing cabinet: bookings and customer records are written here so they exist after the call ends.',
      engineering: 'MVCC transactions, unique constraints as the last line against double-booking (see this repo\'s appointments table), WAL replication to standbys.',
      architecture: 'THE rule this simulator enforces: the database is never on the real-time media path. Turn boundaries may read it; audio frames never wait on it.',
      infrastructure: 'Voice concurrency × naive connection handling = pool exhaustion. A pooler in transaction mode is non-optional at scale.',
      production: 'Watch p99 query time against your turn budget, replication lag against your failover story, and connection counts against the ceiling.',
      architect: 'Split hot call-state (Redis) from durable record (Postgres) early; merge them only when profiling proves you can.',
    },
    onMediaPath: false,
    concepts: ['postgres', 'session-state', 'idempotency'],
  },
  {
    id: 'queue',
    name: 'Message queue',
    short: 'Queue',
    category: 'infrastructure',
    plane: 'control',
    description: 'Buffered asynchronous work: transcript persistence, CRM updates, recording processing, analytics, callbacks — everything that must happen but not *now*.',
    problemSolved: 'Keeps slow, bursty, retryable work off the real-time path, and absorbs spikes that would otherwise become latency.',
    inputs: ['Messages from producers'],
    outputs: ['Messages to consumers, redelivered on failure'],
    protocols: ['AMQP', 'Redis', 'HTTP'],
    latency: { fixedMs: 5, jitterMs: 3 },
    throughputPerInstance: 10000,
    resources: { baseMemMb: 1024 },
    scaling: { axis: 'partitioned', capacityPerInstance: 10000, notes: 'Messages/sec per node assumption. Consumers scale horizontally; ordering needs partition keys.' },
    cost: { unit: 'per-million-requests', usdPerUnit: 0.4, note: 'Managed queue assumption; edit freely.' },
    failureModes: [
      fm({
        kind: 'queue-saturation',
        name: 'Consumer lag',
        callerImpact: 'Nothing — at first. CRM updates arrive minutes late, then hours; then the queue hits its retention limit and drops data.',
        signal: 'Queue depth monotonically rising; oldest-message age climbing.',
        mitigations: ['Autoscale consumers on depth', 'Dead-letter queue + alerting', 'Backpressure: shed lowest-value producers first'],
        defaultProbability: 0.05,
      }),
      fm({
        kind: 'data-loss',
        name: 'Unbounded queue OOM',
        callerImpact: 'An unbounded in-memory queue is a promise to crash later: broker dies and takes unprocessed work with it.',
        signal: 'Broker memory alarm; producers blocked or messages dropped.',
        mitigations: ['Bounded queues with explicit overflow policy', 'Durable/persistent messages for anything that matters'],
        defaultProbability: 0.02,
      }),
    ],
    alternatives: ['Kafka (log semantics, replay, heavier ops)', 'Redis streams (already have Redis)', 'Postgres SKIP LOCKED table (small scale, fewer moving parts)'],
    whyChoose: 'The moment you find yourself doing a CRM write inside a live turn, you need this. Async-by-default for everything the caller does not hear.',
    ifItFails: 'Calls continue perfectly — that is the design working. Side effects delay; a durable queue replays them after recovery.',
    learn: {
      beginner: 'An inbox for work that can wait: "save this transcript", "update the CRM" get done seconds later without slowing the call.',
      engineering: 'Producers enqueue; consumers ack after success; unacked messages redeliver. At-least-once delivery means every consumer must be idempotent.',
      architecture: 'The async/sync sort: if the caller must hear the result this turn, it cannot be queued; everything else should be.',
      infrastructure: 'Queue depth is the single most honest load signal in the system: it is the integral of (arrival rate − service rate).',
      production: 'Rising depth with healthy consumers means under-provisioned consumers; with unhealthy consumers, a poison message — hence dead-letter queues.',
      architect: 'Choose queue vs log (Kafka) by replay needs: queues for tasks, logs for streams of record you may re-read.',
    },
    onMediaPath: false,
    concepts: ['queues', 'backpressure', 'idempotency'],
  },
  {
    id: 'kafka',
    name: 'Kafka / event log',
    short: 'Kafka',
    category: 'infrastructure',
    plane: 'control',
    description: 'A partitioned, replayable event log: every call event, transcript fragment and metric flows through as a durable stream.',
    problemSolved: 'Many independent consumers (analytics, billing, QA, ML training) need the same event stream, at their own pace, with replay.',
    inputs: ['Events from producers'],
    outputs: ['Ordered partitions consumed by many groups'],
    protocols: ['Kafka', 'TCP'],
    latency: { fixedMs: 10, jitterMs: 5 },
    throughputPerInstance: 50000,
    resources: { baseMemMb: 4096, baseCpu: 2 },
    scaling: { axis: 'partitioned', capacityPerInstance: 50000, notes: 'Events/sec per broker assumption; partitions set consumer parallelism — choose them with growth in mind.' },
    cost: { unit: 'per-instance-hour', usdPerUnit: 0.25, note: 'Broker node assumption; edit freely.' },
    failureModes: [
      fm({
        kind: 'queue-saturation',
        name: 'Consumer group lag',
        callerImpact: 'Dashboards and billing fall behind real time; decisions get made on stale data.',
        signal: 'Consumer lag per partition rising.',
        mitigations: ['Scale consumers to partition count', 'Alert on lag age, not message count'],
        defaultProbability: 0.05,
      }),
      fm({
        kind: 'unavailable',
        name: 'Broker/partition unavailability',
        callerImpact: 'Producers buffer or drop events; calls are unaffected if (and only if) producing is fire-and-forget.',
        signal: 'Under-replicated partitions; produce errors.',
        mitigations: ['Replication factor ≥ 3', 'Producer buffering with bounded memory', 'Never produce synchronously from the media path'],
        defaultProbability: 0.01,
      }),
    ],
    alternatives: ['Simple queue (if nobody replays)', 'Kinesis/PubSub (managed equivalents)', 'Postgres outbox (small scale)'],
    whyChoose: 'When more than two systems want the event stream, point-to-point queues turn into spaghetti; a log gives everyone the same truth.',
    ifItFails: 'Real-time calls unaffected; the analytical nervous system goes dark. Durable retention means consumers catch up on recovery.',
    learn: {
      beginner: 'A permanent diary of everything that happened, which many systems read at their own speed.',
      engineering: 'Append-only partitioned log; consumers track their own offsets; retention by time/size; ordering guaranteed within a partition (key by call_id).',
      architecture: 'Queue = task to do once. Log = fact that happened, read by many. Voice platforms emit facts constantly; that is why Kafka appears at scale.',
      infrastructure: 'Partition count is chosen up front and awkward to change: it caps consumer parallelism.',
      production: 'Lag age (how old is the newest unprocessed event) is the SLI; message counts mislead.',
      architect: 'Below ~50k events/day, a Postgres outbox table is honestly fine. Kafka earns its ops burden at real scale — do not cosplay it.',
    },
    onMediaPath: false,
    concepts: ['kafka', 'queues'],
  },
  {
    id: 'object-storage',
    name: 'Object storage',
    short: 'Storage',
    category: 'data',
    plane: 'control',
    description: 'Bottomless, cheap, durable blobs: call recordings, voicemail, model artifacts, exports.',
    problemSolved: 'Recordings are big (a 10-min call ≈ 5–10 MB compressed) and kept for months; block storage and databases are the wrong price and shape.',
    inputs: ['PUT blobs'],
    outputs: ['GET blobs, lifecycle transitions'],
    protocols: ['HTTP'],
    latency: { fixedMs: 60, jitterMs: 40 },
    resources: {},
    scaling: { axis: 'managed-external', capacityPerInstance: 1000000 },
    cost: { unit: 'per-gb-month', usdPerUnit: 0.023, note: 'Example assumption; edit freely.' },
    failureModes: [
      timeoutMode('Upload', 'A recording upload stalls; if uploads are synchronous with call teardown, calls "never end" in your metrics.'),
    ],
    alternatives: ['Filesystem on the server (until the disk fills or the server dies)', 'Database BLOBs (please no)'],
    whyChoose: 'Recording was in the requirements; this is where recordings live. Lifecycle policies handle retention compliance mechanically.',
    ifItFails: 'Buffer locally and retry via the queue. Losing a recording is a compliance event in regulated shops — treat the upload path as seriously as the call path.',
    learn: {
      beginner: 'A giant, cheap hard drive in the cloud where call recordings are kept.',
      engineering: 'HTTP PUT/GET of immutable blobs; multipart upload for large files; presigned URLs so playback never proxies through your servers.',
      architecture: 'Recording forks the media stream at the gateway; the fork must be non-blocking (buffer + async upload), never inline with the live path.',
      infrastructure: '10k calls/day × 8 MB ≈ 80 GB/day ≈ 2.4 TB/month accumulating. Lifecycle to cold storage is a cost lever, not an optimisation.',
      production: 'Retention deletion must be provable for compliance; lifecycle rules + audit beat cron scripts.',
      architect: 'Store the compressed archival format (Opus/FLAC), not raw PCM — 10x storage difference, no audible loss for review purposes.',
    },
    onMediaPath: false,
    concepts: ['recording', 'data-retention'],
  },

  // ==========================================================================
  // PLATFORM
  // ==========================================================================
  {
    id: 'kubernetes',
    name: 'Kubernetes / orchestrator',
    short: 'K8s',
    category: 'infrastructure',
    plane: 'control',
    description: 'Schedules, restarts, scales and rolls out your service fleet. The control plane of your control plane.',
    problemSolved: 'At more than a handful of servers, humans placing processes on machines stops working. Something must reconcile desired vs actual.',
    inputs: ['Deployment specs, autoscale policies'],
    outputs: ['Running pods, rollouts, restarts'],
    protocols: ['HTTP', 'gRPC'],
    latency: { fixedMs: 0 },
    resources: { baseCpu: 1, baseMemMb: 2048 },
    scaling: { axis: 'managed-external', capacityPerInstance: 5000, notes: 'Pods per cluster; managed control planes remove most of the ops burden.' },
    cost: { unit: 'per-instance-hour', usdPerUnit: 0.1, note: 'Control plane assumption; edit freely.' },
    failureModes: [
      fm({
        kind: 'disconnect',
        name: 'Rollout drops live calls',
        callerImpact: 'A deploy SIGTERMs pods holding 50 live calls each. Without drain logic, deploy time = outage time.',
        signal: 'Call-drop spike correlated exactly with deploy events.',
        mitigations: ['preStop drain: stop accepting, wait for calls to end (long grace periods)', 'maxSurge rollouts', 'Deploy windows at low traffic'],
        defaultProbability: 0.05,
      }),
      fm({
        kind: 'overload',
        name: 'Aggressive bin-packing',
        callerImpact: 'CPU-bursty media pods packed tightly start throttling each other; audio quality degrades fleet-wide.',
        signal: 'CPU throttling metrics; audio deadline misses without load growth.',
        mitigations: ['Guaranteed QoS (requests = limits) for media pods', 'Dedicated node pool for the media tier'],
        defaultProbability: 0.03,
      }),
    ],
    alternatives: ['Plain VMs + systemd (simpler, less dynamic)', 'ECS/Cloud Run-class managed runtimes', 'Nomad'],
    whyChoose: 'Autoscaling, self-healing and declarative rollouts — the mechanics the Scaling Lab demonstrates — come nearly free.',
    ifItFails: 'Running pods keep running (data plane independence); you lose the ability to scale, heal and deploy until the control plane returns.',
    learn: {
      beginner: 'The manager robot: notices a crashed server, starts a new one, adds more when it is busy.',
      engineering: 'Controllers reconcile desired state; HPA scales replicas on metrics; probes decide restarts; PodDisruptionBudgets bound how many die at once.',
      architecture: 'The voice twist: pods hold 5–20-minute connections, so termination grace, draining and disruption budgets matter far more than for stateless web pods.',
      infrastructure: 'Scale-out takes image-pull + start + warmup (~1–3 min). Your spike model must cover that gap with headroom.',
      production: 'The classic incident: default 30 s terminationGracePeriod vs 15-minute calls. The fix is a number in YAML and a drain handler.',
      architect: 'Separate node pools: media (guaranteed CPU, few pods/node) vs control (bin-packed). One scheduler, two economies.',
    },
    onMediaPath: false,
    concepts: ['kubernetes', 'autoscaling', 'connection-draining'],
  },
  {
    id: 'monitoring',
    name: 'Observability stack',
    short: 'Monitoring',
    category: 'observability',
    plane: 'control',
    description: 'Metrics, logs and traces for a system whose failures are measured in milliseconds of awkward silence.',
    problemSolved: '"The agent feels slow" is undebuggable without per-stage latency data. Observability turns vibes into graphs.',
    inputs: ['Metrics, structured logs, spans from every component'],
    outputs: ['Dashboards, alerts, traces'],
    protocols: ['HTTP', 'gRPC'],
    latency: { fixedMs: 0 },
    resources: { baseMemMb: 2048, baseCpu: 1 },
    scaling: { axis: 'stateless-horizontal', capacityPerInstance: 100000, notes: 'Sized by events/sec and cardinality, not calls.' },
    cost: { unit: 'per-gb-month', usdPerUnit: 0.5, note: 'Ingest+retention assumption; edit freely.' },
    failureModes: [
      fm({
        kind: 'data-loss',
        name: 'Telemetry gap',
        callerImpact: 'None directly — but the next incident is diagnosed blind.',
        signal: 'The absence of signal is the signal: metrics flatline at zero.',
        mitigations: ['Monitor the monitoring (heartbeats)', 'Local buffer + backfill', 'Never block the app on telemetry'],
        defaultProbability: 0.02,
      }),
    ],
    alternatives: ['Prometheus+Grafana+Tempo/Jaeger (self-hosted)', 'Datadog-class SaaS', 'OpenTelemetry into either'],
    whyChoose: 'The validator flags architectures without it, because production voice systems are diagnosed by latency waterfalls, not by staring at code.',
    ifItFails: 'Calls are fine; engineers are blind. Telemetry must be fire-and-forget so its outage can never become a call outage.',
    learn: {
      beginner: 'The dashboard room: graphs of active calls, delays and errors so people can see problems before callers complain.',
      engineering: 'Metrics (counters/histograms), structured logs with call_id on every line (see this repo\'s logging_setup), and traces: one span per pipeline stage per turn.',
      architecture: 'Design events first, dashboards second: every SimEvent type in this simulator maps to what a real deployment should emit.',
      infrastructure: 'Cardinality is the cost driver: per-call-id metrics explode; per-call-id LOGS and per-region METRICS is the sane split.',
      production: 'Alert on user experience (perceived latency p95, call success rate), page on symptoms, not on every twitching cause.',
      architect: 'The perceived-latency histogram is the north-star chart: every optimisation in this simulator should be visible there, or it did not happen.',
    },
    onMediaPath: false,
    concepts: ['observability', 'opentelemetry'],
  },
]

// -- indexes -----------------------------------------------------------------

export const SPEC_BY_ID: Record<string, ComponentSpec> = Object.fromEntries(
  COMPONENT_SPECS.map((s) => [s.id, s]),
)

export function getSpec(id: string): ComponentSpec {
  const spec = SPEC_BY_ID[id]
  if (!spec) throw new Error(`Unknown component spec: ${id}`)
  return spec
}

export const CATEGORY_LABELS: Record<string, string> = {
  endpoint: 'Endpoints',
  telephony: 'Telephony',
  transport: 'Transport',
  media: 'Media processing',
  speech: 'Speech AI',
  intelligence: 'Intelligence',
  runtime: 'Agent runtime',
  state: 'State',
  data: 'Data',
  infrastructure: 'Infrastructure',
  observability: 'Observability',
  human: 'Humans',
  external: 'External systems',
}
